dequelabs/cauldron

package.json
=> chore: set production NODE_ENV for build

packages/styles/button.css
=> fix(styles): set correct height on thin buttons

package.json, packages/react/__tests__/IconMock.js, packages/react/src/components/Icon/index.tsx, tsconfig.json, yarn.lock
=> chore: Prevent test output from being polluted with Icon exceptions

docs/index.js
=> fix: link to new repo in demo app

docs/patterns/components/TextField/index.js, packages/styles/forms.css, packages/styles/variables.css
See [ux pin](https://preview.uxpin.com/968856563f218051695962d1b39372cacc17821e)
Related: dequelabs/attest-browser-extensions#2354
=> fix: update field inputs and textareas for new design

docs/patterns/components/Button/index.js, packages/styles/base.css, packages/styles/button.css, packages/styles/variables.css
resolves #5 
resolves #42 
resolves #50 
---
=> feat(styles): redesigned buttons

packages/styles/base.css
=> feat(styles): Sets default heading text color

packages/react/src/components/Dialog/index.tsx
=> fix(react): fix dialog not being initialized correctly

packages/react/__tests__/src/components/SkipLink/index.js, packages/react/src/components/SkipLink/index.tsx
=> fix(SkipLink): pass props through to nav dom node

docs/patterns/components/Alert/index.js
=> chore(docs): adds missing import to alert demo

packages/react/src/components/Dialog/index.tsx, packages/react/src/utils/setRef.ts
=> fix(react): makes dialogRef an optional prop for Dialog

packages/react/src/components/Alert/index.tsx, packages/react/src/components/Modal/index.tsx
=> feat: support adding className to alert/modal content/footer

docs/index.html, docs/index.js, docs/patterns/components/TextField/index.css, package.json, packages/styles/forms.css, yarn.lock
=> fix(styles): Updates textfield labels/margins

packages/styles/forms.css
=> fix(styles): align radio labels properly

packages/styles/forms.css
=> fix(styles): tweak checkbox/radio margins

packages/react/src/components/Checkbox/index.tsx, packages/react/src/components/RadioGroup/index.tsx
=> fix(react): make name, value optional for Checkbox and RadioGroup

packages/react/src/components/OptionsMenu/OptionsMenu.tsx
=> fix: make trigger optional prop for OptionsMenu

docs/patterns/components/TextField/index.css, packages/styles/forms.css
Resolve issue https://github.com/dequelabs/cauldron/issues/102
=> fix(styles): Updates font-size of text field to `--text-size-small`

packages/styles/button.css
Resolution to issue https://github.com/dequelabs/cauldron/issues/103 (UM assignment with @allisonkench)
=> fix(styles): Adds pointer cursor to Button with variant link

docs/index.js, docs/patterns/components/Line/index.js, docs/patterns/components/Tooltip/index.css, docs/patterns/components/Tooltip/index.js, packages/react/__tests__/src/components/Line/index.js, packages/react/__tests__/src/components/Tooltip/index.js, packages/react/src/components/Line/index.tsx, packages/react/src/components/Tooltip/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/line.css, packages/styles/tooltip.css
see https://github.com/dequelabs/walnut/issues/1300
=> feat: Adds big Tooltip component

docs/patterns/components/Toast/index.js, packages/react/__tests__/src/components/Toast/index.js, packages/react/src/components/Toast/index.tsx
=> feat(react): allow toast auto-focus to be disabled

packages/react/__tests__/src/components/OptionsMenu/OptionsMenuTrigger.js, packages/react/src/components/OptionsMenu/OptionsMenuTrigger.tsx
- see #55
- [a11y support of aria-haspopup=menu](https://a11ysupport.io/tech/aria/aria-haspopup_attribute\#support-table-4)
=> fix(react): Adds aria-haspopup to options menu trigger

docs/patterns/components/Icon/index.js, packages/react/src/components/Icon/icons/new.svg
Adds the new icon for https://github.com/dequelabs/axe-extension/issues/606
=> feat(react): add "new" icon

packages/react/src/components/Dialog/index.tsx
=> fix(react): Make Dialog's `onClose` optional

packages/styles/options-menu.css
=> fix(styles): Adds sufficient focus indication to options menu items

docs/index.js, docs/patterns/components/Tag/index.js, packages/react/__tests__/src/components/Tag/index.js, packages/react/src/components/Tag/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/tag.css, packages/styles/variables.css
=> feat: Adds tag component

docs/patterns/components/Icon/index.js, packages/react/src/components/Icon/icons/filter.svg
Added new filter icon to Cauldron according to the uxpin design.
=> feat: add filter icon to icon package

packages/react/src/components/Icon/index.tsx
=> fix(react): allows radio's icon to be appear checked (icon)

.circleci/canary-version.js, .circleci/config.yml, .versionrc.json, CHANGELOG.md, CONTRIBUTING.md, RELEASING.md, lerna.json, netlify.toml, package.json, packages/react/package.json, packages/react/yarn.lock, packages/styles/package.json, packages/styles/yarn.lock, yarn.lock
This release contains some security/dependency updates, but is really for testing the new release process (#215).
=> chore(release): 0.1.1

.github/workflows/sync-branches.yml
=> ci: Automatically sync master and develop

.github/workflows/sync-branches.yml, CHANGELOG.md, docs/patterns/components/IconButton/index.js, package.json, packages/react/__tests__/src/components/Icon/index.js, packages/react/package.json, packages/react/src/components/Icon/index.tsx, packages/react/src/components/IconButton/index.tsx, packages/styles/button.css, packages/styles/icon-button.css, packages/styles/package.json, packages/styles/variables.css
- **react:** implement icon button variants ([#181](https://github.com/dequelabs/cauldron/issues/181)) ([20ca9b2](https://github.com/dequelabs/cauldron/commit/20ca9b2add710024dc7b25a3acde58e50d6d50cf))
- **react:** use offscreen container instead of aria-label for icon elements ([#228](https://github.com/dequelabs/cauldron/issues/228)) ([07d748d](https://github.com/dequelabs/cauldron/commit/07d748d895bc805dd958dcdff35d5ce0a74e27cf))
=> chore: release 0.1.2

docs/patterns/components/Select/index.js, packages/react/__tests__/src/components/Select/index.js, packages/react/package.json, packages/react/src/components/Select/index.tsx, packages/react/yarn.lock
=> feat(react): allows select component to be controlled

docs/Demo/index.js, docs/index.js, docs/patterns/components/Table/index.js, package.json, packages/react/__tests__/src/components/Table/index.js, packages/react/src/components/Table/Table.tsx, packages/react/src/components/Table/TableBody.tsx, packages/react/src/components/Table/TableCell.tsx, packages/react/src/components/Table/TableHead.tsx, packages/react/src/components/Table/TableHeader.tsx, packages/react/src/components/Table/TableRow.tsx, packages/react/src/components/Table/index.ts, packages/react/src/index.ts, packages/styles/index.css, packages/styles/table.css, packages/styles/variables.css, yarn.lock
This is a minimal implementation of the cauldron table (#202)
what this does **NOT** support:
- sortability
- responsiveness (the "mobile view" table repeater thing from the uxpin)
=> feat: Adds simple table

docs/index.js, docs/patterns/components/TooltipTabstop/index.css, docs/patterns/components/TooltipTabstop/index.js, packages/react/__tests__/src/components/TooltipTabstop/index.js, packages/react/src/components/TooltipTabstop/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/tooltip-tabstop.css
=> feat(react): add TooltipTabstop component

packages/react/package.json, packages/react/yarn.lock
[Because security](https://github.com/advisories/GHSA-gj77-59wh-66hg)
=> chore(react): Update `react-syntax-highlighter`

docs/index.js, packages/react/__tests__/src/contexts/theme.js, packages/react/src/contexts/theme.tsx, packages/react/src/index.ts
=> feat(react): Adds theme provider

docs/patterns/components/TextField/index.css, docs/patterns/components/TextField/index.js, packages/react/src/components/TextField/index.tsx, packages/styles/forms.css, packages/styles/variables.css
closes #102
closes #87
closes #175
=> feat: style updates to TextFields (and better docs)

docs/patterns/components/Icon/index.js, packages/react/src/components/Icon/icons/download.svg
feat: add download icon
Needed for multi-buy invoice downloads.
=> feat: add download icon

docs/patterns/components/Toast/index.js, packages/react/__tests__/src/components/Toast/index.js, packages/react/src/components/Toast/index.tsx, packages/react/src/components/Toast/utils.ts
=> feat(Toast): Adds support for error type

docs/Demo/index.js, docs/index.js, docs/patterns/components/Stepper/index.css, docs/patterns/components/Stepper/index.js, packages/react/__tests__/src/components/Stepper/index.js, packages/react/src/components/Stepper/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/stepper.css
This patch implements the "light theme" stepper. Support for the dark theme will be added in a separate PR (which we can then use in the extensions IGT progress thing)
=> feat: Adds stepper (progress) component

packages/react/__tests__/src/components/IconButton/index.js, packages/react/src/components/IconButton/index.tsx
=> fix(performance): do not render tooltip when an icon button is disabled

packages/react/__tests__/src/components/SkipLink/index.js, packages/react/src/components/SkipLink/index.tsx
fix: skip link text missing space
axe-extension#1761
=> fix: skip link text missing space

packages/react/src/components/IconButton/index.tsx
fix: optional icon button props
=> fix: optional icon button props

packages/styles/base.css, packages/styles/loader.css
This is needed for issue: https://github.com/dequelabs/axe-extension/issues/1596
=> feat: apply themes to Loader and LoaderOverlay

packages/styles/code.css, packages/styles/dialog.css, packages/styles/icon-button.css, packages/styles/side-bar.css, packages/styles/top-bar.css
fix: dark/light theme for sidebar, modal, code
A few updates suggested by @awpearlm 
- sidebar hover
- iconbutton color
- modal border
- code colors
#316
=> fix: dark/light theme for sidebar, modal, code

packages/styles/top-bar.css
Topbar link colors were applying to _all_ links.
=> fix(styles): fix TopBar links styles applying to all anchor elements

packages/react/__tests__/src/components/Select/index.js, packages/react/src/components/Select/index.tsx, yarn.lock
- **update**: `onChange` prop to be optional
- **update**: removes default value from function signature to be assigned later if prop value is nullish
Closes issue: #389
=> fix(select): updates onChange prop to be optional

.circleci/config.yml, packages/styles/button.css, packages/styles/icon-button.css, packages/styles/variables.css, yarn.lock
Ref: dequelabs/axe-extension/issues/1930
=> fix(styles): Adds expected dark/light theme focus rings

packages/styles/select.css
=> fix(styles): prevent focus ring from causing layout shift on select focus

docs/index.js, docs/patterns/components/Address/index.js, packages/react/__tests__/src/components/Address/index.js, packages/react/src/components/Address/index.tsx, packages/react/src/index.ts, packages/styles/address.css, packages/styles/index.css
Add a set of Address components for https://github.com/dequelabs/walnut/issues/2488
=> feat: add Address component

CONTRIBUTING.md
=> docs: document our BEM naming syntax

packages/react/src/components/Checkbox/index.tsx, packages/react/src/components/RadioGroup/index.tsx, packages/styles/forms.css
fixes #400 
fixes #401
fixes #403
=> fix(styles): adjust styles of checkbox/radio to match set designs

packages/react/__tests__/src/components/Tabs/Tabs.js, packages/react/src/components/Tabs/Tabs.tsx
This is needed for dequelabs/axe-extension#1809 to react to when the active tab changes.
=> feat(react): add onChange prop to tabs when the active tab changes

packages/react/__tests__/src/components/IconButton/index.js, packages/react/src/components/IconButton/index.tsx
This closes https://github.com/dequelabs/cauldron/issues/309
=> fix: Add aria label to disabled IconButton

docs/patterns/components/Table/index.js, packages/styles/table.css
This pr implements dark theme to Table
=> fix: Implement dark theme to Table

packages/styles/tag.css
This pr closes: https://github.com/dequelabs/cauldron/issues/406
=> fix: Implement dark theme to Tag

packages/styles/layout.css
This closes: https://github.com/dequelabs/cauldron/issues/396
=> fix: Change focus outline colors for main

packages/styles/base.css, packages/styles/layout.css
=> fix(styles): ensure that scrollbars match light/dark scheme

netlify.toml
=> chore: Delete Netlify config

docs/index.js, docs/patterns/components/IssuePanel/index.js, docs/patterns/components/Panel/index.js, packages/react/__tests__/src/components/IssuePanel/index.js, packages/react/__tests__/src/components/Panel/index.js, packages/react/src/components/IssuePanel/index.tsx, packages/react/src/components/Panel/index.tsx, packages/react/src/components/Tabs/Tabs.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/issue-panel.css, packages/styles/panel.css
BREAKING CHANGE: The panel implementation has been replaced, including removing props that are not used in the new implementation
This will be used in https://github.com/dequelabs/walnut/issues/2558
The old Panel has been renamed to IssuePanel
=> feat: replaced the panel implementation with a new one to match our pattern library

docs/Demo/PropDocs.js, docs/index.js, docs/patterns/components/Pagination/index.js, packages/react/__tests__/src/components/Pagination/index.js, packages/react/src/components/Pagination/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/pagination.css
=> feat(react,styles): Adds pagination component

.github/workflows/preview-cleanup.yml
Also cleanup previews after their PR has been closed
=> ci: Allow building deploy previews after initial commit

docs/patterns/components/Tabs/index.js, packages/react/src/components/Tabs/Tabs.tsx, packages/styles/tabs.css
<details>
<summary>Vertical Tabs - Dark</summary>
</details>
<details>
<summary>Vertical Tabs - Light</summary>
</details>
closes #496
=> feat(react): add vertical orientation for tabs

docs/patterns/components/Panel/index.js, packages/react/__tests__/src/components/Panel/index.js, packages/react/src/components/Panel/index.tsx, packages/styles/panel.css
Needed for https://github.com/dequelabs/walnut/issues/2558
=> feat: add collapsed prop to panel

packages/react/src/components/Pagination/index.tsx
this should resolve the final issue for #386 🎉
=> fix(react): Ensure pagination items have accessible names in resting state

docs/index.js, docs/patterns/components/Breadcrumb/index.js, packages/react/__tests__/src/components/Breadcrumb/index.js, packages/react/src/components/Breadcrumb/Breadcrumb.tsx, packages/react/src/components/Breadcrumb/BreadcrumbItem.tsx, packages/react/src/components/Breadcrumb/BreadcrumbLink.tsx, packages/react/src/components/Breadcrumb/index.ts, packages/react/src/index.ts, packages/styles/breadcrumb.css, packages/styles/index.css
=> feat(react,styles): add breadcrumb component

docs/patterns/components/Breadcrumb/index.js
Quick fix for invalid positive tab index
=> fix(docs): fix positive tabIndex for breadcrumb docs

docs/patterns/components/RadioGroup/index.js, packages/react/__tests__/src/components/RadioGroup/index.js, packages/react/src/components/RadioGroup/index.tsx, packages/styles/forms.css
=> feat(radiogroup): add labelDescription prop to radio items

docs/patterns/components/Panel/index.js, packages/react/src/components/Panel/index.tsx
Needed in https://github.com/dequelabs/walnut/issues/2665
=> fix: Make Panel heading optional

packages/styles/table.css
closes https://github.com/dequelabs/cauldron/issues/516
=> fix: Make Table width uneven

docs/patterns/components/Link/index.js, packages/react/__tests__/src/components/Link/index.js, packages/react/src/components/Link/index.css, packages/react/src/components/Link/index.tsx
Needed for https://github.com/dequelabs/walnut/issues/2696
=> feat: add support for button-secondary to link

packages/styles/forms.css, packages/styles/select.css
Ref: https://github.com/dequelabs/cauldron/issues/538
=> fix: Add missing margin to TextField and Select

packages/react/__tests__/src/components/Toast/index.js, packages/react/src/components/DescriptionList/index.tsx, packages/react/src/components/Toast/utils.ts, packages/styles/table.css
Ref: https://github.com/dequelabs/cauldron/issues/550; https://github.com/dequelabs/cauldron/issues/551
Part of https://github.com/dequelabs/walnut/issues/2961
=> fix: Add hover state to Table and correct Toast icon

README.md
=> docs: links to contributing doc in readme

packages/styles/toast.css
=> fix(styles): fix color contrast issue with toast dismiss button in dark theme

packages/react/src/components/Icon/icons/minus.svg
adds a `minus` icon
Closes issue: #610
=> feat(icons): add minus

packages/styles/button.css
fixes an issue discovered when we ran screenshot tests in another project
=> fix(styles): fix thin buttons being too large

packages/react/__tests__/src/utils/useSharedRef.js, packages/react/src/components/LoaderOverlay/index.tsx, packages/react/src/utils/useSharedRef.ts
=> fix(react): create useSharedRef util to share refs on forwardRef functional components

docs/patterns/components/TwoColumnPanel/index.js, packages/react/__tests__/src/components/TwoColumnPanel/index.js, packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx, packages/styles/two-column-panel.css
https://github.com/dequelabs/cauldron/issues/598
=> feat(react): add skip link to 2 column panel

docs/patterns/components/Code/index.js, packages/react/__tests__/src/components/Code/index.js, packages/react/src/components/Code/index.tsx
ref: https://github.com/dequelabs/cauldron/issues/625
=> feat(react): allow tabindex to be set for code component

packages/react/__tests__/src/components/Panel/index.js, packages/react/src/components/Panel/index.tsx
This PR allows a ref to be forwarded to the Panel's section, which makes it possible to sen programmatic focus to the Panel.
=> feat: add ref forwarding to Panel component

CONTRIBUTING.md
=> chore: document steps to add an Icon

packages/react/package.json
=> fix(react): Allow usage with React v18

packages/react/src/components/Icon/icons/recycle-square.svg
=> feat(react): add `recycle-square` icon

docs/patterns/components/Button/index.js, packages/react/__tests__/src/components/Button/index.js, packages/react/src/components/Button/index.tsx, packages/styles/button.css
Required for https://github.com/dequelabs/walnut/pull/3320
=> feat(button): add option to render as tag

docs/patterns/components/Pagination/index.js, packages/react/__tests__/src/components/Pagination/index.js, packages/react/src/components/Pagination/Pagination.tsx, packages/styles/pagination.css
this is needed for https://github.com/dequelabs/axe-extension/pull/2636
=> feat(react,styles): adds thin modifier to pagination

packages/styles/tooltip.css
Closes https://github.com/dequelabs/cauldron/issues/409
=> feat(styles): update tooltip styles to support dark theme

docs/patterns/components/TwoColumnPanel/index.js, packages/react/__tests__/src/components/TwoColumnPanel/index.js, packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx
=> feat(react): allow custom media query to be set for the TwoColumnPanel collapsing

docs/patterns/components/Accordion/index.js, packages/react/__tests__/src/components/Accordion/index.js, packages/react/src/components/Accordion/Accordion.tsx
This is needed for https://github.com/dequelabs/axe-extension/issues/2476 and addresses some outstanding issues.
=> fix(react): fix issue where accordion would not pass through props correctly

docs/patterns/components/Toast/index.js, packages/react/__tests__/src/components/Toast/index.js, packages/react/src/components/Toast/index.tsx
Needed for https://github.com/dequelabs/axe-extension/issues/2621
=> feat(react): allow Toasts to not be dismissible

packages/react/__tests__/src/components/Tabs/Tabs.js
Looks like I forgot to push the test for #728 🤦
=> chore: increase tabs test coverage for focus

packages/styles/variables.css
For these colors I copied the colors of issues used elsewhere in walnut. However, the axe issue colors required in the project page do not match those colors. This fixes the colors to those used in the uxpin.
=> fix(styles): correct axe issue colors

packages/styles/forms.css
=> fix(styles): do not shift content when input elements gain focus

docs/Home/index.js
This PR adds content requested by marketing to the homepage for Hacktoberfest '22:
- The purpose of the resource
- Guidelines for how to use it
- Who made it (Deque)
- A path to submit contributions and bugs
- A call to action to try Deque tools to test for a11y
Issue #738
I'm using a feature branch to break up the new footer, homepage content, and SEO into smaller PRs for review. Plus, I expect some back and forth on wording, etc.
=> docs: homepage content

docs/Demo/Footer.js, docs/index.css, docs/index.js
Marketing request for Hacktoberfest: A footer, with link back to [deque.com](http://deque.com/) and a link to the open-source terms surrounding this project.
- create component with footer tag
- add copyright, link to deque.com, link to terms of use, and link to MPL-2.0 License
- position sidebar and layout so they're not blocked by the footer
Issue #739
=> docs: footer

docs/Home/index.js, docs/index.js
- homepage copy updates from marketing
- add title and description for SEO
Issue #742
=> docs: homepage SEO

docs/index.js
- add "accessible component pattern" to component page titles
- add meta description tag to component pages
Issue #741 and #740
=> docs: component page title and description

.github/ISSUE_TEMPLATE/BUG.yml
Create issue template for bug reports
Closes: #744
=> docs: create issue template

CONTRIBUTING.md, docs/patterns/components/Alert/index.js, docs/patterns/components/IssuePanel/index.js, docs/patterns/components/Modal/index.js, docs/patterns/components/ProgressBar/index.js
This PR contains fixes for a few typos in the docs and `CONTRIBUTING.md`.
=> docs: fix typos

docs/patterns/components/Table/index.js
=> fix(docs): Gives table demo delete buttons unique names

docs/patterns/components/ClickOutsideListener/index.js, packages/react/src/components/ClickOutsideListener/index.tsx
Add Demo component to ClickOutsideListener docs page.
Related to issue #783
=> docs: Add Demo component to ClickOutsideListener docs page #783

docs/patterns/components/TopBar/index.js
- added prop table for TopBar component for https://github.com/dequelabs/cauldron/issues/806 this issue
=> docs: added prop table for TopBar component

packages/react/src/components/Tooltip/index.tsx
Closes https://github.com/dequelabs/cauldron/issues/689
=> fix(react): use CustomEvent for tooltip events

docs/patterns/components/Layout/index.js
=> docs: props table for Layout component docs page

packages/styles/icon-button.css
=> fix(IconButton): Ensure anchor and button icons are aligned

docs/patterns/components/Link/index.js, packages/react/__tests__/src/components/Link/index.js, packages/react/src/components/Link/index.css, packages/react/src/components/Link/index.tsx
=> fix: allow users to use thin link button

packages/styles/variables.css
Closes: https://github.com/dequelabs/cauldron/issues/858
=> fix: update css variable for moderate/serious

docs/patterns/components/Table/index.js, packages/react/__tests__/src/components/Table/index.js, packages/react/src/components/Table/TableFooter.tsx, packages/react/src/components/Table/index.ts, packages/react/src/index.ts, packages/styles/table.css
Closes: #860 
<details>
<summary>TableFooter</summary>
Dark Theme:
Light Theme: 
</details>
=> feat(table): create table footer component

docs/Demo/index.css, packages/styles/pagination.css
Closes: #861 
<details>
<summary>Pagination</summary>
320px:
Ï
</details>
=> fix(pagination): remove unnecessary margins

packages/styles/link.css
closes: https://github.com/dequelabs/cauldron/issues/886
=> fix(styles): improves contrast of Link when in hover state

packages/styles/dialog.css, packages/styles/pointout.css, packages/styles/variables.css
=> fix: added icon size variable and applied to current icons

packages/styles/base.css, packages/styles/variables.css
Added styling to prevent the font-family from being overwritten for elements within a button. 
Closes #888
=> fix(styles): overwrote base button font-family (#888)

packages/styles/tag.css
Closes https://github.com/dequelabs/cauldron/issues/926
=> fix(styles): allow Tag to adjust width based on content

CONTRIBUTING.md
=> docs: add breaking changes definition

packages/styles/navbar.css
As requested by @bobbyomari I made the following adjustments to the NavItem css:
- use `--font-weight-normal` for nav items unless they're active, in which case, use `--font-weight-medium`
=> fix(NavBar): adjust styling for nav items

.gitignore, packages/styles/select.css
=> fix: fix overflow behavior of Select component

docs/patterns/components/Pagination/index.js, docs/props.js, packages/react/src/components/Pagination/Pagination.tsx, packages/react/src/types.ts
Closes https://github.com/dequelabs/cauldron/issues/955
=> feat(react): allow pagination labels to take react nodes

docs/components/Navigation.tsx
Ensure the the mapped items have a key.
=> docs: fix keys for document navigation

CONTRIBUTING.md, docs/pages/styles.mdx
Including some baseline style guidelines.
=> docs: add style guidelines

.github/workflows/release.yml
=> chore: fix invalid release action yaml

docs/pages/styles.mdx, docs/pages/theming.mdx
=> docs: document theming in cauldron

docs/pages/components/Offscreen.mdx, packages/react/src/components/Offscreen/index.tsx
=> fix(react): fix incorrect proptype for Offscreen component and update documentation to v2

packages/react/__tests__/src/components/NavBar/NavItem.js, packages/react/src/components/NavBar/NavItem.tsx
=> feat(NavBar): ensure NavBar sets aria-current=true by default on active items

docs/readme.md
=> docs: include a readme for basic usage of documentation

packages/styles/variables.css
- Adds new color variable to match with what is in the [pattern library UXPin color guide](https://preview.uxpin.com/styleguide/520e80315786a67ba43a3ca50598e6d69782627c#/colors-guide) and [panel UXPin](https://preview.uxpin.com/520e80315786a67ba43a3ca50598e6d69782627c#/pages/161871161/specification/sitemap?mode=i)
=> feat(styles): adds darker colored warning variable

packages/styles/code.css
=> fix(styles): fix inaccessibile syntax highlight colors

docs/pages/components/Select.mdx, packages/react/__tests__/src/components/Select/index.js, packages/react/src/components/Select/index.tsx
Closes https://github.com/dequelabs/cauldron/issues/1090
=> feat(react): allow Select label to be a ReactNode

packages/styles/button.css
Removed the css property making all buttons text appear as upper case as described by issue #1069
=> feat(styles): removed unwanted text transform property

packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx
=> fix: updated TwoColumnPanel to not override children keys

docs/pages/components/RadioGroup.mdx
=> docs: do not use headings for RadioGroup group label

packages/react/__tests__/src/components/Accordion/index.js, packages/react/__tests__/src/components/ExpandCollapsePanel/ExpandCollapsePanel.js, packages/react/src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
=> feat(react): respect prefers-reduced-motion when opening/closing ExpandCollapsePanel or Accordion

docs/pages/components/Tooltip.mdx
=> docs: include note for recommending TooltipTabstop over Tooltip

packages/styles/forms.css
=> fix: fixes overflow bug on text-field and text-area

packages/styles/table.css
=> fix(table): position sort icons using flex-start

packages/react/__tests__/src/components/TwoColumnPanel/index.js, packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx
=> fix(react): fix issue where TwoColumnPanel would not collapse correctly with reduced motion

packages/styles/accordion.css
closes #902 
This is a temporary fix until we can fully implement the design with #856
=> fix(react): fix color contrast issue for accordion trigger on hover

packages/styles/variables.css
=> feat(styles): update focus-dark color to better contrast against different backgrounds

packages/styles/forms.css
=> feat(styles): apply a fixed size to radio/checkbox inherited from icon-size

packages/react/src/components/Combobox/Combobox.tsx
=> fix(react): ensure that no results get announced for NVDA

docs/components/example.css, packages/styles/code.css
=> feat(styles): update styles for Code component

packages/styles/forms.css, packages/styles/variables.css
=> fix(styles): fix color contrast for selected listbox options

docs/pages/components/Breadcrumb.mdx
=> docs: set aria-current on breadcrumb docs

docs/pages/components/Checkbox.mdx
=> docs: wrap checkbox list example with a role="group"

packages/styles/two-column-panel.css
=> fix(styles): prevent overflow for TwoColumnPanel left container at narrow viewports

docs/pages/components/Modal.mdx, packages/react/__tests__/src/components/Dialog/index.js, packages/react/src/components/Dialog/index.tsx, packages/styles/alert.css, packages/styles/dialog.css, packages/styles/utilities.css, packages/styles/variables.css
=> feat(Modal): sync modal styles with pattern library and include alignment props

packages/react/src/components/Tooltip/index.tsx
=> fix: tooltip content cut off at reflow

docs/pages/components/TagButton.mdx, packages/react/__tests__/src/components/TagButton/index.js, packages/react/src/components/TagButton/index.tsx, packages/react/src/index.ts, packages/styles/index.css, packages/styles/tag-button.css, packages/styles/variables.css
=> feat(TagButton): add new tag button component

docs/pages/components/Combobox.mdx, packages/react/__tests__/src/components/Combobox/index.js, packages/react/src/components/Combobox/Combobox.tsx
Closes: https://github.com/dequelabs/cauldron/issues/1295 https://github.com/dequelabs/cauldron/issues/1296
=> feat(Combobox): allow combobox to take an input ref

docs/pages/components/Table.mdx, packages/styles/table.css
=> fix(styles): use correct border for table headers with row headings

packages/styles/navbar.css
=> fix(style): removed double bottom border and added padding for < 64 rem

packages/styles/button.css
=> fix(react,styles): keep rest background for disabled:active button state

packages/react/src/components/Combobox/Combobox.test.tsx, packages/react/src/components/Combobox/Combobox.tsx
=> fix(Combobox): set aria-activedescendant correctly when listbox is expanded with selected value

packages/react/src/components/Combobox/Combobox.test.tsx, packages/react/src/components/Combobox/Combobox.tsx
=> fix(react): fix incorrect aria when Combobox has no results

packages/react/src/components/TextField/TextField.test.tsx
Typescript was getting upset over this.
=> chore: fix lint error in TextField test

packages/react/.eslintrc.js, packages/react/jest.config.ts, packages/react/package.json, packages/react/rollup.config.js, packages/react/src/setupTests.ts, packages/react/tsconfig.json
This restores types that are missing from the lib.
=> fix(react): restore missing types from lib

packages/react/src/components/Pagination/Pagination.tsx
=> fix: fix toast bug where screen readers dont read toast

docs/pages/components/SearchField.mdx, packages/react/src/components/SearchField/SearchField.test.tsx, packages/react/src/components/SearchField/index.tsx
=> fix(react): update input value for SearchField in controlled case

docs/components/CopyToClipboardButton.tsx
closes #1395 
This is primarily to address the a11y issue raised, and a more comprehensive approach should be taken with #1445 which should replace the work being done here.
=> docs: prevent more than one toast notification from appearing for copy actions

docs/components/CopyToClipboardButton.tsx
fixes ts error and build issue in app
=> docs: fix docs build issue

.github/workflows/update-browserslist-db.yml
closes #1422
This should generate a PR to update the browserlist database on a schedule or with a manual run. (see example PR: https://github.com/dequelabs/cauldron/pull/1453)
=> ci: add action to update the browserslist database on a monthly basis

packages/styles/timeline.css
=> fix(styles): fix issue with text overflow leading to timeline details to be misaligned

packages/styles/base.css, packages/styles/index.css, packages/styles/typography.css, packages/styles/variables.css
Closes: [#1570](https://github.com/dequelabs/cauldron/issues/1570)
=> feat(styles): added new typography system

packages/styles/breadcrumb.css
Closes: [#1582](https://github.com/dequelabs/cauldron/issues/1582)
=> fix(styles): synced breadcrumb with design

docs/pages/components/Tooltip.mdx, packages/react/src/components/Tooltip/Tooltip.test.tsx, packages/react/src/components/Tooltip/index.tsx
=> feat(react): fix show prop and add defaultShow prop

docs/pages/components/Badge.mdx, packages/react/src/components/Badge/index.test.tsx, packages/react/src/components/Badge/index.tsx, packages/react/src/index.ts, packages/styles/badge.css, packages/styles/index.css
=> feat(react): added badge component

packages/react/README.md
Adds attribution for Font Awesome.
https://fontawesome.com/license
https://fontawesome.com/license/free
=> docs: add font awesome attribution

packages/styles/notice.css
Closes: [#1648](https://github.com/dequelabs/cauldron/issues/1648)
=> feat(styles): synced `notice` styles

packages/react/src/components/BottomSheet/screenshots.e2e.tsx
=> test: fix screenshots not being captured for all components

packages/styles/tabs.css
=> feat(styles): synced tabs with design

docs/pages/components/Listbox.mdx, packages/react/src/components/Combobox/ComboboxOption.tsx, packages/react/src/components/Listbox/Listbox.tsx, packages/react/src/components/Listbox/ListboxContext.tsx, packages/react/src/components/Listbox/ListboxOption.tsx, packages/react/src/components/Listbox/index.test.tsx, packages/react/yarn.lock
=> feat(react): add multiselect to Listbox component

docs/pages/components/AnchoredOverlay.mdx, docs/pages/components/Popover.mdx, docs/pages/components/Tooltip.mdx, packages/react/package.json, packages/react/src/components/AnchoredOverlay/AnchoredOverlay.test.tsx, packages/react/src/components/AnchoredOverlay/index.tsx, packages/react/src/components/Code/Code.test.tsx, packages/react/src/components/Pagination/Pagination.tsx, packages/react/src/components/Popover/index.tsx, packages/react/src/components/TextEllipsis/TextEllipsis.test.tsx, packages/react/src/components/Tooltip/index.tsx, packages/react/src/index.ts, packages/react/yarn.lock, packages/styles/popover.css, packages/styles/tooltip.css
=> feat(react,style): add AnchoredOverlay component, refactor Tooltip and Popover to use AnchoredOverlay

packages/react/src/components/Combobox/Combobox.tsx, packages/react/src/components/Select/index.tsx, packages/react/src/components/TextField/index.tsx
=> feat(react): hide required text in label for AT

CONTRIBUTING.md
=> docs: correct proprietary spelling

packages/react/src/components/TextEllipsis/index.tsx
=> fix(react): fix incorrect tooltipProps for TextEllipsis

docs/pages/components/TextEllipsis.mdx, packages/react/src/components/TextEllipsis/TextEllipsis.test.tsx, packages/react/src/components/TextEllipsis/index.tsx
=> feat(react): allow tooltip to be hidden for text ellipsis

.github/workflows/tests.yml
Housekeeping to ensure we're not overusing actions.
=> ci: cancel in-progress test runs

packages/react/src/components/TextEllipsis/index.tsx
=> fix(react): fix overflow callback not being called for TextEllipsis when tooltip is hidden

packages/styles/description-list.css
=> fix(styles): apply overflow hidden for DescriptionList to contain overflow items

packages/react/src/components/ImpactBadge/index.test.tsx, packages/react/src/components/ImpactBadge/index.tsx
=> feat(react): remove icon from ImpactBadge

.github/workflows/create-release-pr.yml, .github/workflows/sync-branches.yml
=> chore: use machine user for sync and release-pr actions

packages/react/src/components/ActionList/ActionList.tsx, packages/react/src/components/Listbox/Listbox.tsx, packages/react/src/components/Listbox/index.test.tsx
=> fix(react): fix a11y issue where selected listbox options did not fire click handlers

docs/pages/components/Checkbox.mdx, docs/pages/components/Combobox.mdx, docs/pages/components/FieldWrap.mdx, docs/pages/components/RadioCardGroup.mdx, docs/pages/components/RadioGroup.mdx, docs/pages/components/SearchField.mdx, docs/pages/components/Select.mdx, docs/pages/components/TextField.mdx
Followup to https://github.com/dequelabs/walnut/pull/12529#discussion_r2388773323
=> docs: clarify when input components should/must use FieldWrap
