dequelabs/cauldron

packages/styles/modal.css

<details>
<summary>BEFORE</summary>
</details>
<details>
<summary>AFTER</summary>
</details>

fix(styles): make heading take up full modal header height

---

packages/styles/modal.css

A few modal layout changes are needed to help address: https://github.com/dequelabs/attest-browser-extensions/issues/2330

fix: use flexbox for modal layouts and include default spacing in the content

---

packages/styles/dialog.css

Another fixed element adjacent to a dialog would push it out of the way. We should at a minimum, fix it to the top of whatever it's containing relative element is.

fix(styles): ensure that dialogs are anchored to the top of its relative container

---

.github/PULL_REQUEST_TEMPLATE.md
.github/review.yml

This patch removes the PR template and sets up the review app in its place. If merged, I'll make the review app a required check.

chore: Replace PR checkbox with review app

---

docs/Demo/index.js
docs/patterns/components/Tooltip/index.js
packages/react/__tests__/src/components/Tooltip/index.js
packages/react/package.json
packages/react/src/components/Tooltip/index.tsx
packages/react/src/global.d.ts
packages/react/src/index.css
packages/react/yarn.lock
packages/styles/tooltip.css
packages/styles/variables.css

BREAKING CHANGE:
The api for for implementing a tooltip has changed.
Instead of `<Tooltip><button /><Tooltip>`, the tooltip takes a target ref or html element. 
```jsx
<Tooltip target={ref}>tooltip</Tooltip>
<button ref={ref}>button</button>
```
Closes #113

feat(react): implement new tooltips, replacing rc-tooltip

---

packages/styles/button.css
packages/styles/icon-button.css
packages/styles/variables.css

I was apparently working off an older version of the pattern/style guide so this contains the "fixed" styles:
* Buttons should match the height of `thin` button variants
* Fixed the focus ring to use the right color

fix(react): fix button styles according to the style guide

---

packages/react/__tests__/src/components/Toast/index.js
packages/react/src/components/Toast/index.tsx
packages/styles/toast.css

BREAKING CHANGE: children are no longer rendered within a direct-child span element

feat: support any node type in toast children

---

packages/react/__tests__/reactSyntaxHighlighterMock.js
packages/react/package.json
packages/react/src/components/Code/index.tsx

It looks like the [default recommendation](https://github.com/react-syntax-highlighter/react-syntax-highlighter#light-build) for `react-syntax-highlighter` to create a light build is _still_ importing all of the languages, greatly increasing the bundle size:
<details>
<summary>before webpack bundle (~1mb)</summary>
</details>
Directly importing the `Light` module should greatly reduce the size and avoid side effects.

fix(react): directly import Light syntax highlighter to avoid side effects and limit the number of languages bundled

---

packages/react/__tests__/src/components/Tooltip/index.js
packages/react/src/components/Tooltip/index.tsx

This addresses the dismissable portion of [WCAG 2.1 - 1.4.13: Content on Hover or Focus](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html).

 fix(react): allow tooltip to be hidden on escape keypress

---

packages/react/__tests__/src/components/Icon/index.js
packages/react/src/components/Icon/index.tsx

Adds `forwardRef` and a corresponding test so that users can reference the Icon component.
Closes: #148

feat: add forwardRef to icon component

---

docs/Demo/index.js
docs/patterns/components/Button/index.js
packages/react/__tests__/src/components/Button/index.js
packages/react/src/components/Button/index.tsx
packages/styles/button.css

- **add**: startIcon and endIcon props that will place an `Icon` in `Button` either before or after button text
- **add**: tests to verify proper elements are added when an Icon is passed to either prop
- **refactor**: update `Button` code to be a Stateless Functional Component
Closes: #141

feat(button): handle style icons as children inside of buttons

---

packages/react/src/components/Pointout/index.tsx
packages/styles/pointout.css

@schne324 and I worked through how the pointout should handle focus order, and based on https://github.com/dequelabs/axe-extension/issues/470#issuecomment-759088732 it feels natural to have Close → Content → Previous → Next in the tab order for the pointout.

fix(react): move next/prev pointout buttons to after content to allow for a more natural tab order

---

packages/react/src/components/Icon/index.css
packages/styles/icon-button.css

The icon was hijacking pointer events from being picked up by the underlying button.

fix: remove pointer events from iconbutton icon

---

packages/react/src/components/Icon/index.css
packages/styles/icon-button.css

We shouldn't apply inherit styles to icon as consumers may want to size them differently. Individual components that use Icons should be able to freely override their sizes.

fix(styles): remove height/width styles from Icon

---

packages/styles/button.css

@schne324 noticed that buttons were being displayed weird in the extension. `inline-grid` restores the original layout (`inline-block`) while allowing for grid elements in the button.

fix(styles): use inline-grid for buttons to fix layout issues

---

packages/styles/icon-button.css

I noticed the outline ring on hover did not match the background color of the button

fix(styles): use the same outline color for IconButton as the background

---

packages/styles/button.css

Replaces layered drop shadows with pseudo-element drop shadow for better focus/hover indicators.
Primary button hover:
Primary button focus:

fix(styles): use before pseudo element for button indicators

---

docs/patterns/components/Pointout/index.js
packages/react/src/components/Pointout/index.tsx
packages/styles/pointout.css

This is needed for the extension to address some positioning issues with pointouts, and to allow for some more flexibility in where the pointout is.

feat: allow pointouts to specify their positioning in alignment with their target element

---

packages/react/src/components/Icon/index.tsx

We see these not mounted errors occasionally appearing in the extension, this should help clean them up

fix(react): prevent memory leaks in Icon component

---

packages/react/__tests__/src/components/IconButton/index.js
packages/react/src/components/IconButton/index.tsx

*update*: icon button ref was just internal for the tooltip, adds ability to use ref freely

feat(icon-button): exposes ref prop

---

.circleci/canary-version.js
.circleci/config.yml
.versionrc.json
RELEASING.md
lerna.json
netlify.toml
package.json
packages/react/package.json
packages/styles/package.json
yarn.lock

This patch removes [Lerna](https://lerna.js.org/). Lerna is too complicated for what we want to do here, and it [didn't work when we tried to make our first "stable" release](https://circleci.com/gh/dequelabs/cauldron/1760?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). Instead we:
- release with [`standard-version`](https://github.com/conventional-changelog/standard-version) and a simple Node.js program for calculating "canary" version numbers
- run `build` and `dev` npm scripts via [`concurrently`](https://www.npmjs.com/package/concurrently)
Additionally we've documented our release process (see `RELEASING.md`) so maintainers don't have to guess how this works.

build: Remove Lerna

---

packages/react/__tests__/src/components/Icon/index.js
packages/react/src/components/Icon/index.tsx

Some screen readers don't read `aria-label` on generic elements, so moving this to an offscreen container.

fix(react): use offscreen container instead of aria-label for icon elements

---

packages/react/src/components/Code/index.tsx

This patch adds support for syntax highlighting YAML.
The axe Linter documentation site needs this. I've tried manually registering the language in the site, but the TypeScript compiler gets _very_ angry with me and React emits tons of prop type warnings.

feat(react): Support YAML highlighint in Code component

---

packages/react/src/components/Dialog/index.tsx
packages/styles/dialog.css

The scrim had some issues, namely that it was layered on top of the scrollbar and prevented the scrollbar from being directly interacted with, even while the outer container containing the modal was scrollable.

fix(react): use background color instead of scrim for proper scrolling with dialogs

---

docs/patterns/components/Select/index.css
docs/patterns/components/Select/index.js
packages/react/__tests__/src/components/Select/index.js
packages/react/src/components/Select/index.tsx
packages/styles/forms.css
packages/styles/select.css

BREAKING CHANGE: selects now have parity with `<TextField />` s in that they always render an `.Error` div. This causes a slight layout difference with more space below each `<Select />`.  The text "Required" will now show up with any `<Select />` who is passed a `true` required prop.
closes #89

feat(Select): Adds support for required/error

---

packages/react/__tests__/src/components/Loader/index.js
packages/react/src/components/Loader/index.tsx

BREAKING CHANGE: Loader component now set role, aria-valuetext, aria-busy, aria-valuemin, and aria-valuemax instead of making a generic role (div) have an aria-label.
closes #53
| Browser+AT | Readout |
|-------------|----------|
| Safari+VO    | Loading..., indeterminate, progress indicator |
| FF+NVDA    |  progress bar busy. Loading... |

feat(react): Sets progressbar attributes on Loader

---

CHANGELOG.md
docs/patterns/components/Alert/index.js
docs/patterns/components/Select/index.css
docs/patterns/components/Select/index.js
docs/patterns/components/TextField/index.css
docs/patterns/components/TextField/index.js
docs/patterns/components/Toast/index.js
package.json
packages/react/__tests__/src/components/Loader/index.js
packages/react/__tests__/src/components/Select/index.js
packages/react/__tests__/src/components/Toast/index.js
packages/react/package.json
packages/react/src/components/Alert/index.tsx
packages/react/src/components/Loader/index.tsx
packages/react/src/components/Select/index.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/components/Toast/index.tsx
packages/react/src/components/Toast/utils.ts
packages/styles/forms.css
packages/styles/package.json
packages/styles/select.css
packages/styles/variables.css

- **react:** Loader component now set role, aria-valuetext, aria-busy, aria-valuemin, and aria-valuemax instead of making a generic role (div) have an aria-label
- **Select:** selects now have parity with <TextField /> s in that they always render an .Error div. This causes a slight layout difference with more space below each <Select />. The text "Required" will now show up with any <Select /> who is passed a true required prop.
- **react:** Sets progressbar attributes on Loader ([#289](https://github.com/dequelabs/cauldron/issues/289)) ([f865166](https://github.com/dequelabs/cauldron/commit/f8651666a321fa02a418152e97ad908cd429f3e4)), closes [#53](https://github.com/dequelabs/cauldron/issues/53)
- **Select:** Adds support for required/error …

Release 2021 07 28

---

packages/styles/top-bar.css

fix: eliminate light specific vars for top-bar
Defines single vars that are set differently for each theme.
#323

fix: eliminate light specific vars for topbar

---

packages/react/__tests__/src/components/TextField/index.js
packages/react/src/components/TextField/index.tsx

closes: #352 
When a `value` prop is passed in, set the input `value` directly instead of from state. There's also no longer any need to update state with value on `componentDidUpdate` because of this change. This eliminates the issue where the cursor would jump to the end upon updating the value described in #352.
- the input value prop was always being set from state
- the `onChange` function of `TextField` was not updating state if a `value` prop was present
- `setState` was being called with the `value` prop on `componentDidUpdate`, which was causing the cursor to jump

fix(react): cursor jump caused by updating state on componentDidUpdate

---

packages/react/__tests__/src/components/Stepper/index.js
packages/styles/dropdown.css
packages/styles/panel.css
packages/styles/toast.css
packages/styles/top-bar.css

fix: more top-bar related styles for dark/light theme
- fixes topbar dropdown to show at the end of the topbar as in uxpin
- fixes toasts to keep same text color for both themes as described in uxpin
- removes topbar's bottom border for dark theme as in uxpin
uxpin: https://preview.uxpin.com/5a35f510bfb55e3e77f9dbd54a49203736113855#/pages/139526426/simulate/sitemap
https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465422/simulate/no-panels
#316

fix: more top bar and panel related styles for dark/light theme

---

packages/react/src/components/OptionsMenu/OptionsMenu.tsx

For the issue, please check: https://github.com/dequelabs/cauldron/issues/271
This needs to be fixed to implement ApiKey table in Walnut. For the ticket, please see: https://github.com/dequelabs/walnut/issues/2446

fix: Match types of OptionsMenuTriggerProps

---

packages/react/src/components/OptionsMenu/OptionsMenu.tsx

This is a continuation of https://github.com/dequelabs/cauldron/pull/393; `OnClick `and `ref` in `OptionsMenu` also have type discrepancies with types in `OptionMenuTriggerProps`.
Is there anything we can do to catch this earlier? Our demo is mostly javaScript, if we use typescript, will we be able to catch these issues before we merge?

fix: type issues of OptionsMenu

---

packages/react/src/components/ProgressBar/index.tsx
packages/react/src/components/Tabs/Tabs.tsx
packages/react/src/global.d.ts
packages/react/src/types.ts

These changes are only needed in `3.0`, so no need to backport.
see #428

fix(react): import cauldron namespace from types where needed

---

CHANGELOG.md
package.json
packages/react/package.json
packages/react/src/components/ProgressBar/index.tsx
packages/react/src/components/Tabs/Tabs.tsx
packages/react/src/global.d.ts
packages/react/src/types.ts
packages/styles/package.json

- **react:** import cauldron namespace from types where needed ([#429](https://github.com/dequelabs/cauldron/issues/429)) ([400a919](https://github.com/dequelabs/cauldron/commit/400a919d600a09e233b20b245e62a1d4c5af7cd1))

chore(release): v3.0.1

---

docs/index.js

resolves 1 issue type for the new a11y tests (#386):
> All page content should be contained by landmarks

fix(docs): sets banner role on topbar to resolve axe-core issue

---

docs/Demo/index.js
docs/patterns/components/Address/index.js
docs/patterns/components/DescriptionList/index.js
docs/patterns/components/LoaderOverlay/index.js

resolves 1 issue type for the new a11y tests (#386):
> Scrollable region must have keyboard access

fix(docs): Makes code blocks focusable regions to allow keyboard users to scroll them

---

docs/index.js

resolves 1 issue type for the new a11y tests (#386):
> Ensures landmarks are unique
---
VO readout:
> Link, skip to Main Content, Skip, navigation
ever so slightly redundant but resolve an axe-core issue by giving this navigation element a unique accessible name

fix(docs): gives skip nav a unique accessible name

---

packages/react/src/components/Address/index.tsx

Typescript didn't like that these elements returned false. It expects `JSX.Element` to either be an element or null

fix: render null instead of false in empty cases

---

packages/styles/select.css

The pr fixes the margin-bottom with background color for dark theme select:
Not very visible in Cauldron, but very obvious in extension:

fix: remove unused background color for disabled select

---

packages/styles/dialog.css

This will only affect dialogs with a fixed height

fix: Correct dialog content padding according to design

---

packages/react/src/components/Table/TableCell.tsx
packages/react/src/components/Table/TableHeader.tsx

Currently, the way the types are set up, we can't set any attributes on `TableHeader` or `TableCell` except `className`. We should be able to set things like `scope` and `colspan`.
We've had to set `TableHeader` to `any` to get around this: https://github.com/dequelabs/walnut/pull/2042/files#diff-c0d076ba97b24a2d7584c89ff60baf472ce1e33c4b9399c3c3b9befac61527b6R23
Related: https://github.com/dequelabs/cauldron/issues/288

fix: allow TableHeader to take th attributes and TableCell to take td attributes

---

docs/patterns/components/Stepper/index.js
packages/react/__tests__/src/components/Stepper/index.js
packages/react/src/components/Stepper/index.tsx

This patch adds a new `tooltipText="..."` prop to the `<Step/>` component when using it in tooltip mode. This enables us to add an explicit accessible name to the underlying `<button/>`, which prevents axe-core from raising the following issue:
> Buttons must have discernible text
See https://axe.deque.com/issues/5b594e52-53b4-4ed4-8a41-bc22a630fb73
Closes #445

fix(Step): Add an accessible name when using `tooltip={...}`

---

packages/styles/toast.css

fix(styles): set close button for toast to have a minimum height of 24px

---

packages/react/__tests__/src/components/SideBar/index.js
packages/react/src/components/SideBar/SideBar.tsx

Closes: https://github.com/dequelabs/cauldron/issues/327

fix: Add navProps to SideBar component

---

docs/patterns/components/Loader/index.js
packages/react/__tests__/src/components/Loader/index.js
packages/react/src/components/Loader/index.tsx

JAWS was only reading the `role="alert"` element when navigating through the dom when there is name from contents, and not `aria-label`. 
closes #423

fix(react): update loader to address issues with being announced in JAWS

---

packages/styles/link.css

needed to fix an a11y issue found in #386

fix(styles): update the link color to be set correctly for light/dark modes

---

packages/styles/tag.css

This pr closes: https://github.com/dequelabs/cauldron/issues/407

fix: Tag value font weight should be medium

---

packages/styles/forms.css
packages/styles/select.css

A previous pr makes `Error div` render conditionally: https://github.com/dequelabs/cauldron/pull/441
However, the `margin-bottom` value which belongs to `.Error` class and is supposed to take effect all the time, also renders conditionally. This pr moves this `margin-bottom` value to `Error div`'s parent components, so that it will always render.
This is related to issues like this extremely narrow margin between the two fields in Web app:

fix: Move Error margin bottom to its parent

---

.circleci/config.yml
packages/react/package.json
packages/react/rollup.config.js
packages/react/yarn.lock

This is a follow up to #486, it took me a while to figure out why SVGs were still not rendering correctly so details are below:
After #486 `viewBox` was not being set for some of the SVGs, after a bit of debugging it appears that `svgo` was removing any `viewBox` attributes that exactly matched the `height` and `width` values. Normally this would be fine, but we scale icons in different spots so we always want the SVG to scale according to the viewbox and not implicit height/width attributes. This PR addresses a couple of things:
* Always include the original `viewBox` dimensions
* Standardize all svg height/width to `24px` (this can be overridden with css styles)
* Optimize SVG output to not include `hash`, this is a slight size reduction since the svgs will be imported by their file …

fix(react): ensure that icons are set with viewbox and standard height/width values

---

.github/workflows/preview.yml

A **super cool** undocumented feature of AWS Amplify is that deployment previews are not supported for open source repos. This patch implements an action which works around this limitation and _should_ create a preview for every opened PR.

build: Setup Amplify PR deployment previews

---

docs/patterns/components/LoaderOverlay/index.js
packages/react/src/components/LoaderOverlay/index.tsx
packages/styles/loader.css

Fixing a couple of regressions with the loader:
- Allow `label` and `variant` props to be set for the loader overlay. (Since they are not included in the propTypes, they can't be set)
- Restore the default layout styles for the loader (previously, was `50px auto`)

fix: fix loader

---

packages/react/src/components/Tooltip/index.tsx

This fixes a tooltip performance issue where the `useEffect` was intending to be acting on the `show` prop, but there was also an internal function named `show` causing the tooltip to re-run the useEffect for every render exponentially adding event listeners eventually causing anything using this to be very slow or crash.

fix(react): fix tooltip performance issue

---

packages/react/package.json
packages/react/yarn.lock

It seems `@rollup/plugin-dynamic-import-vars` was accidently added as a production/runtime dep. This patch corrects that.

fix(react): Do not require build-time dependencies in production

---

docs/patterns/components/Checkbox/index.js
packages/react/__tests__/src/components/Checkbox/index.js
packages/react/src/components/Checkbox/index.tsx
packages/styles/forms.css

add: new prop (optional) for `labelDescription` that can be used to provide additional context to checkbox options
update: CSS style for error when paired with `labelDescription` as requested by @awpearlm 
closes: #527

feat(checkbox): add labelDescription prop

---

packages/styles/tooltip.css

The tooltips were still reserving space on the page when hidden, leading to double scroll bars in some cases (ex: https://github.com/dequelabs/walnut/issues/2330 and https://github.com/dequelabs/walnut/issues/2583). We still want them to be rendered, though, so that they can be used as labels (aria-labeledby). This PR changes the tooltip positioning to `fixed` when hidden so that they don't take up room.

fix: do not reserve space for tooltip when hidden

---

docs/patterns/components/Pagination/index.js
packages/react/__tests__/src/components/Pagination/index.js
packages/react/src/components/Pagination/index.tsx

Fixing _x of y of total_ to _x to y of total_

fix(react): use correct grammar for pagination start/end text

---

packages/styles/card.css

I have a pagination inside of a card pattern, but the list items there are showing a border on the bottom:

fix(styles): fix unnecessary border from lists inside of cards

---

packages/react/src/components/Stepper/index.tsx

This patch updates the `react` package's `<Step/>` component's type definitions, allowing it to accept any `<li>` props. Additionally, we're no longer adding an invalid `tooltipText={...}` prop to the `<li>`, which prevents the following warning from the tests:
```
console.error node_modules/react-dom/cjs/react-dom.development.js:88
Warning: React does not recognize the `tooltipText` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tooltiptext` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in li (created by Step)
in Step (created by WrapperComponent)
in WrapperComponent
```

fix(react): Allow `Step` to accept any LI props

---

packages/styles/button.css

fix(styles): allow button text to wrap to prevent text from being cut off

---

packages/react/README.md
packages/react/src/components/Dialog/index.tsx
packages/react/src/components/Pointout/index.tsx
packages/react/src/components/SkipLink/index.tsx
packages/react/src/components/Tooltip/index.tsx
packages/react/src/utils/is-browser/index.ts
packages/react/src/utils/query-all/index.ts
packages/react/src/utils/viewport/index.ts

This change allows platforms like GatsbyJS and NextJS, which use SSR engines for production builds, to render pages that use the Cauldron library without running into errors caused by references to `window`-related objects, such as `document`, in the NodeJS runtime.
Not every instance of `window` and `document` need to be switched - only those which are executed when a component is rendered. References to browser-specific objects are safe in lifecycle methods and effect hooks, so this PR doesn't touch those.
- Resolves #481.
- Incidentally, also resolves https://github.com/dequelabs/product-docs-site/issues/72

fix(react): ensure browser environment before accessing browser-related objects

---

packages/styles/forms.css

closes #585 
closes #590
closes #584 
I tested with Voiceover, JAWS 2021, and NVDA with the included changes and everyone read out radios/checkboxes both as tabstops and with navigation keys.

fix(styles): fix issue which prevents navigation/tabstop in NVDA/Chrome on Checkboxes/Radios

---

CHANGELOG.md
package.json
packages/react/package.json
packages/styles/button.css
packages/styles/package.json

- **styles:** fix thin buttons being too large ([#613](https://github.com/dequelabs/cauldron/issues/613)) ([a5ffb23](https://github.com/dequelabs/cauldron/commit/a5ffb233b64f9aca3971ca47ed795185b224d155))

chore: release 4.2.1

---

packages/react/src/components/Table/TableHeader.tsx

Changes to the `aria-sort` attribute on table column cells is not yet [widely supported](https://a11ysupport.io/tech/aria/aria-sort_attribute) and is only currently announced in Firefox/JAWS.
This does mean that anyone using Firefox/JAWS will get a _very verbose_ announcement for sorting changes - but every other SR combination will at least have a polite announcement of the sort change.

feat(react): announce changes to sort on sortable TableHeaders

---

CHANGELOG.md
package.json
packages/react/__tests__/src/components/SkipLink/index.js
packages/react/__tests__/src/utils/useSharedRef.js
packages/react/package.json
packages/react/src/components/Icon/icons/minus.svg
packages/react/src/components/LoaderOverlay/index.tsx
packages/react/src/components/SkipLink/index.tsx
packages/react/src/components/Table/TableHeader.tsx
packages/react/src/utils/useSharedRef.ts
packages/styles/button.css
packages/styles/package.json
packages/styles/skip-link.css

- **icons:** add minus ([#611](https://github.com/dequelabs/cauldron/issues/611)) ([abded4e](https://github.com/dequelabs/cauldron/commit/abded4e2c730f6716abab598eccbc2a066b97cbf))
- **react:** announce changes to sort on sortable TableHeaders ([#622](https://github.com/dequelabs/cauldron/issues/622)) ([01c786a](https://github.com/dequelabs/cauldron/commit/01c786aea73440a6aedc9b79af2944b974d23b1d))
- **react:** create useSharedRef util to share refs on forwardRef functional components ([#597](https://github.com/dequelabs/cauldron/issues/597)) ([d153945](https://github.com/dequelabs/cauldron/commit/d15394566685da7ff50bb70924be80d316834bc4))
- **skip-link:** fix skip-link styles with new design ([#607](https://github.com/dequelabs/cauldron/issues/607)) …

chore(release): 4.3.0

---

packages/styles/base.css

Adds an additional fix for: https://github.com/dequelabs/cauldron/issues/567
Allows text in buttons to wrap to prevent content from being cut off at 320px

fix(styles): allow buttons to wrap

---

docs/patterns/components/ExpandCollapsePanel/index.js
packages/react/__tests__/src/components/ExpandCollapsePanel/PanelTrigger.js
packages/react/src/components/ExpandCollapsePanel/PanelTrigger.tsx

Adds 2 new optional props:
- `expandedIcon`
- `collapsedIcon`
This enables devs to use alternatives to the `chevron-right` and `chevron-down` icons.
Closes: #633

feat(PanelTrigger): add icon override

---

docs/patterns/components/Table/index.js
packages/react/__tests__/src/components/Table/index.js
packages/react/src/components/Table/TableHeader.tsx

Ref: https://github.com/dequelabs/walnut/issues/3098
The issue was we were defaulting the sort message to `sortDescendingAnnouncemen`
Note: I also corrected the spelling of the `sortDescendingAnnouncemen` prop to be `sortDescendingAnnouncement`. This prop was undocumented, so I don't think we need a new major release. I also added documentation.

fix: correct default sort announcement

---

packages/styles/navbar.css
packages/styles/top-bar.css

In meeting with @awpearlm, the padding on top bar and nav items should be 16px--not 18px.

fix: correct top bar padding

---

docs/patterns/components/IconButton/index.js
packages/react/__tests__/src/components/IconButton/index.js
packages/react/src/components/IconButton/index.tsx

This allows a node to be passed in as the label for an IconButton. Allowing a node to be passed in allows consumers to include things like screen reader-only content. (see the docs example in this PR)

feat: allow a node to be passed in as an IconButton label

---

docs/patterns/components/LoaderOverlay/index.js
packages/react/__tests__/src/components/LoaderOverlay/index.js
packages/react/src/components/LoaderOverlay/index.tsx

Sometimes, the `LoaderOverlay` component needs to also be a focus trap, since its potentially blocking active content behind the overlay while something is loading.

feat(react): allow LoaderOverlay to be used as a focus trap

---

packages/react/src/components/Table/Table.tsx
packages/react/src/components/Table/TableBody.tsx
packages/react/src/components/Table/TableCell.tsx
packages/react/src/components/Table/TableHead.tsx
packages/react/src/components/Table/TableHeader.tsx
packages/react/src/components/Table/TableRow.tsx

`children` and `classNames` are already a part of the default props. Also added native table prop types for elements missing them.

chore(table): clean up interfaces and use native types

---

package.json
packages/react/yarn.lock
yarn.lock

dependencies with vulnerabilities that can be resolved with `--fix`
Also it appears `less` is no longer used, so removing.

chore: update dependencies

---

packages/react/__tests__/src/components/Loader/index.js
packages/react/src/components/Loader/index.tsx

This patch adds support to passing a `ref={React.createRef()}` to the `<Loader />` component.

feat(react): Add `ref` support to `<Loader/>`

---

packages/react/src/components/LoaderOverlay/index.tsx

This fixes an issue where focus-trap handles keyboard trapping only and does not isolate the trapped component for SR users.

fix(react): ensure that other elements get correctly hidden when setting focusTrap on overlay loader

---

.github/workflows/semantic-pr-title.yml
CHANGELOG.md
package.json
packages/react/__tests__/src/components/Loader/index.js
packages/react/__tests__/src/components/Panel/index.js
packages/react/package.json
packages/react/src/components/Loader/index.tsx
packages/react/src/components/LoaderOverlay/index.tsx
packages/react/src/components/Panel/index.tsx
packages/styles/package.json

- **react:** Add `ref` support to `<Loader/>` ([#651](https://github.com/dequelabs/cauldron/issues/651)) ([f8ca4e9](https://github.com/dequelabs/cauldron/commit/f8ca4e9b0465f085394206878ceff0d4c39fb290))
- add ref forwarding to Panel component ([#649](https://github.com/dequelabs/cauldron/issues/649)) ([77fc218](https://github.com/dequelabs/cauldron/commit/77fc21838a462f7403013c8c121ea2db7f1f1071))
- **react:** ensure that sibling elements get correctly hidden when setting focusTrap on overlay loader ([#656](https://github.com/dequelabs/cauldron/issues/656)) ([2f777a4](https://github.com/dequelabs/cauldron/commit/2f777a4317d0aa51db0e66c1749a9f5488b9eed4))

chore(release): 4.5.0

---

packages/styles/radio-card.css

Error: `autoprefixer end value has mixed support consider using flex-end instead`

fix(RadioCardGroup): use `flex-end` instead of `end` for checked card

---

packages/react/__tests__/src/components/Dialog/index.js
packages/react/package.json
packages/react/src/components/Code/index.tsx
packages/react/src/components/Dialog/index.tsx
packages/react/src/components/ExpandCollapsePanel/PanelTrigger.tsx
packages/react/src/components/FieldWrap/index.tsx
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/IssuePanel/index.tsx
packages/react/src/components/LoaderOverlay/index.tsx
packages/react/src/components/OptionsMenu/OptionsMenu.tsx
packages/react/src/components/Panel/index.tsx
packages/react/src/components/Pointout/index.tsx
packages/react/src/components/SideBar/SideBarItem.tsx
packages/react/src/components/Tabs/Tab.tsx
packages/react/src/components/Tabs/TabPanel.tsx
packages/react/src/components/TextField/index.tsx
packages/react/src/components/Toast/index.tsx
packages/react/src/components/Tooltip/index.tsx
packages/react/src/components/TopBar/TopBarTrigger.tsx
packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx
packages/react/src/utils/polymorphic-type/index.ts
packages/react/tsconfig.json
packages/react/yarn.lock

This patch updates `@deque/cauldron-react` to play nicely with [React v18 types](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions).
Part of https://github.com/dequelabs/walnut/issues/3349

fix(react): Support React 18 types

---

packages/styles/variables.css

Required for https://github.com/dequelabs/walnut/pull/3320.
Colors taken from https://github.com/dequelabs/walnut/blob/develop/app/src/modules/app/components/RuleHelp.css#L95-L119

feat(styles): add axe-core issue impact colors

---

packages/react/src/components/Breadcrumb/BreadcrumbLink.tsx

Having the props extend only `HTMLAttributes<HTMLLinkElement>` did not include things like `href`. Extending `LinkHTMLAttributes<HTMLLinkElement>` brings in some Link specific attributes and extends `HTMLAttributes<HTMLLinkElement>`.

fix(BreadcrumbLink): TS would not allow href attribute on component

---

packages/react/src/components/Accordion/Accordion.tsx
packages/react/src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
packages/react/src/components/ExpandCollapsePanel/PanelTrigger.tsx

This is to fix some issues that I noticed the other day as I was using it, as well as some TypeScript errors being thrown that needed to be fixed (the underlying functionality was fine, this just fixes PropType/TypeScript issues).

fix(react): fixes incorrect PropType and TypeScript interfaces

---

packages/styles/pagination.css

When the pagination controls are right aligned, this removes the right most margin preventing the pagination controls from being aligned to the right border of the containing element.

fix(styles): remove right margin from right most pagination button

---

packages/react/src/components/Pagination/Pagination.tsx

Assign types to the `onClick` props otherwise TS will shout: 
```
Type '(event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void' is not assignable to type '() => void'.ts(2322)
```

fix(react): add types to Pagination onClick props

---

packages/react/package.json
packages/react/yarn.lock

A bug was introduced in ts-node 10.8.1 that made nyc coverage reports included the absolute file path tacked on to the end of the relative path. The change was reverted in 10.8.2. See: https://github.com/TypeStrong/ts-node/issues/1790

fix: upgrade ts-node to fix coverage reports

---

packages/react/__tests__/src/components/Pagination/index.js
packages/react/src/components/Pagination/Pagination.tsx
packages/react/src/components/Pagination/usePagination.tsx

- Expose setCurrentPage from usePagination Hook, allowing developers to manage pagination in certain cases.
- Add a test to make sure that pagination handles the call to setCurrentPage correctly.

feat(react): include setCurrentPage for pageStatus with usePagination hook

---

packages/styles/accordion.css

This may be useful later for https://github.com/dequelabs/cauldron/issues/675, but the existing css selectors were very specific making it difficult to extend the default accordion usage.

fix(styles): remove unnecessary specificity for accordion styles

---

packages/styles/accordion.css

kudos to @tbusillo for noticing this
The recent cleanup with #723 missed that buttons needed a more specific selector because they also inherit from `.ExpandCollapsePanel__trigger`. Including the fallback selector will create a higher specificity while allowing the existing classname to be extended.

fix(styles): fix accordion background colors

---

packages/react/src/components/Tabs/Tabs.tsx

This fixes an issue where `<Tab ref={tabRef}>` was always `null` because it was getting clobbered within `cloneElement`.

fix(react): fix issue where ref property was getting clobberd on <Tab>

---

packages/styles/variables.css

ref: https://github.com/dequelabs/cauldron/issues/715

fix(app): ensure tooltips are not displayed behind a dialog

---

packages/react/src/components/Icon/icons/check-circle.svg
packages/styles/radio-card.css

ensure the check-circle background color defaults to white. to avoid color-contrast issues, currently when used with `RadioCardGroup` we do not meet the 3 : 1 requirements: 
After:

fix(react): ensure check-circle icon meets color-constrast requirements

---

packages/styles/tooltip.css

Closes https://github.com/dequelabs/cauldron/issues/726

fix(styles): fix tooltip arrow positioning when zoomed

---

docs/Demo/index.css

fix(docs): Ensures content doesn't get cutoff in prop docs tables

---

packages/styles/table.css

Update `.TableHeader--sort-decscending` to `.TableHeader--sort-descending`

fix(typo): descending misspelled in table CSS

---

packages/styles/table.css

This reverts commit 87de5e625038316bcc501d848398be03d642ca08.
About two weeks ago in our #pattern-library channel, we discussed that this change should be labeled as "breaking" so that is why we are reverting it.

Revert "fix(typo): descending misspelled (#782)"

---

packages/react/src/components/Icon/index.tsx

fix(react): change div element to span in Icon component for better semantics.
When Icon component is used inside p tag it is not valid HTML, because Icon component uses div element. Replace div element with span, so the Icon can be used inside p tags and it is considered valid HTML.
Closes #668

fix(react): change div element to span in Icon component

---

packages/react/src/components/LoaderOverlay/index.tsx

Add missing export so users can extend the `LoaderOverlay` component.

fix(LoaderOverlay): export LoaderOverlayProps interface

---

packages/styles/tooltip.css

Closes: #707 
I also removed the `font-size` property for `.TooltipContent` because it was using a css variable that didn't exist.

fix(styles): use css variables for big tooltip font size and padding

---

docs/patterns/components/NavBar/index.js

- left out `initialActiveIndex` because it's not used
- fixed "mobil" typos
Closes #804

docs: props table for NavBar component docs page

---

README.md
webpack.config.js

When running the axe server's dependencies locally (`dc.sh up -d`), `:8000` is already taken by DynamoDB. This patch changes the Cauldron dev server's port to 8003 to avoid this conflict.

build: Change dev server port to avoid conflicts

---

packages/styles/options-menu.css

Adds spacing between purple outline and the border of the focused options menu item to address an a11y color contrast issue.
fixes: #877

fix(OptionsMenu): add spacing between focus outline and border

---

packages/styles/variables.css

This PR adds new variables based from new UX pin. 
\cc @bobbyomari

feat(app): add new spacing and colour variables

---

packages/styles/table.css

This PR fixes a bug that was causing the table header to use `--table-header-sorting-background-color` by default even when the table header wasn't sorted.
[UXPin - Tables](https://preview.uxpin.com/68df515d0023cc4b79f25d43f7663e24e363b1b9#/pages/141465418/simulate/sitemap?mode=i)
Screenshot from UXPin Light Theme
Screenshot from UXPin Dark Theme
This change is fixing a breaking change in 5.0.0. Would that mean that the version bumps to 5.0.1?

fix: remove base TableHeader from sort styles

---

packages/react/src/components/Offscreen/index.tsx

`div` elements are not allowed as a child of `button` or `span` elements.
Issue #834 
```
<!doctype html>
<html lang="en">
<title>Test</title>
</html>
```

fix: use a span instead of div for offscreen text

---

packages/styles/breadcrumb.css

Updated the breadcrumbs so the separators will stay inline, while also still wrapping for the cases where there is a large number of breadcrumbs. 
Closes: #850 
Below is an example where it is still multiple columns and one where it is shrunk down to one column due to screen width.

fix(styles): updated breadcrumbs to wrap at low content consistently

---

packages/styles/link.css

Updated the color used for links within paragraphs to use the recommended styling for dynamic color changes.
Closes #884

fix(styles): updated links within paragraphs to use dynamic link color

---

packages/styles/panel.css

Exposing the `Panel` component's padding through a `--panel-padding`  variable allows consumers to override it and/or set negative margins based on it to get children that span the entire width of the `Panel`

feat(styles): expose panel padding through a --panel-padding variable

---

docs/Demo/index.js
docs/patterns/components/Pagination/index.js
packages/react/__tests__/src/components/Pagination/index.js
packages/react/src/components/Pagination/Pagination.tsx

Closes https://github.com/dequelabs/cauldron/issues/703
Trying to manage focus when child components are replaced seems error-prone. Instead, I got rid of the tabstop component and made the button component behave like the tabstop component when disabled.

fix(react): maintain focus on pagination button when last or first page is reached

---

packages/styles/two-column-panel.css

Reverts dequelabs/cauldron#929
These changes caused the focus highlights to get cut off. We'll need to figure out a different way to address scrolling

fix(styles): undo changes to make two panel layout scrollable

---

packages/styles/two-column-panel.css

closes https://github.com/dequelabs/cauldron/issues/786

fix(react): Make TwoColumnPanel wrap to prevent content from getting cut out

---

packages/react/__tests__/src/components/IconButton/index.js
packages/react/src/components/IconButton/index.tsx

Closes https://github.com/dequelabs/cauldron/issues/961

fix(react): only render icon button label where it is needed

---

docs/index.css
docs/patterns/components/Toast/index.js
packages/react/src/components/Toast/index.tsx
packages/styles/toast.css

This pr makes non-dismissible toasts static so they don't cover up content.
Closes: https://github.com/dequelabs/cauldron/issues/954

feat(Toast): make non-dismissible toasts positioned statically

---

packages/styles/description-list.css

Closes #907 
Wraps the side of the description, however, it does not wrap the term. This is intentional because if the term was too long it would lead to other issues but I am open to including the terms too!

fix: updated details to wrap text at smaller widths (#907)

---

docs/components/Example.tsx
docs/remark-plugins.mjs

I noticed that some of the react examples were getting intermingled with the [mdx components](https://github.com/dequelabs/cauldron/blob/develop/docs/mdx-components.tsx) causing some weird layout issues. Wrapping the rendered code in a named function seems to resolve that problem.
The following markdown:
````markdown
```jsx example
<Button>Hello</Button>
```
````
Will now end up transformed into something like:
```mdx
export function CodeExample1234() {
return <><Button>Hello</Button></>
}
{
<Example>
<CodeExample1234 />
</Example>
}
```

docs: fix markdown intermingling with react components

---

.github/workflows/release.yml
RELEASING.md

closes #922
Standardize/simplify our release process by migrating to use [`release-please`](https://github.com/googleapis/release-please)

chore: add release-please as github action

---

docs/pages/components/Checkbox.mdx

I thought the example component had the right background color, but it looks like we still need `FieldWrap` here.

docs: fix accessibility issues on checkbox documentation

---

packages/styles/button.css

fix(Button): ensure button.Link variant inherits its font-size to match inline text

---

.github/workflows/create-release.yml
RELEASING.md
scripts/release.sh

Some more light automation allowing anyone to create cauldron releases from a github action dispatch.
(see https://github.com/dequelabs/cauldron/pull/1042 as an example of one that was run via an action)

ci: add github action for creating releases

---

packages/styles/toast.css

Closes #829
Corrected the toast padding to top and bottom padding of 8 px and left/right to 16px.

fix(react): corrected toast component's padding

---

packages/styles/button.css

Closes: #620 
Please let me know if there is any additional styling that needs to be added or if there is a prototype the styling should be based on.
Before:
After:

fix(react): removed line height styling from thin button

---

package.json
yarn.lock

These packages appear to not be used at the root level (but are defined in `packages/react`).

chore: remove jsdom/jsdom-global from package root

---

packages/styles/select.css

fix(styles): prevent select text from overlapping with carat indicator

---

docs/pages/components/Panel.mdx
packages/styles/panel.css

There was a disproportionate amount of spacing between the heading/content section that is unnecessary:

fix(styles): fix spacing between PanelHeading and PanelContent

---

packages/react/__tests__/src/components/Checkbox/index.js
packages/react/src/components/Checkbox/index.tsx

Closes https://github.com/dequelabs/cauldron/issues/1094

fix(react): allow onBlur and onFocus to be passed to Checkbox without messing up focus state

---

docs/components/Drawer.tsx

Noticed that the escape handler did not correctly detect the open state of the drawer, meaning that esc would not close the drawer. 🤦

docs(accessibility): fix issue where esc key would not close navigation drawer

---

docs/pages/components/Checkbox.mdx
packages/react/src/components/Checkbox/index.tsx
packages/react/src/components/RadioGroup/index.tsx
packages/styles/forms.css

Closes #627 
Relates to #949 
Relates to #1034 
Relates to Walnut [#5739](https://github.com/dequelabs/walnut/issues/5739)
Current behavior:
https://github.com/dequelabs/cauldron/assets/60084578/b94f6133-0c7c-4368-9277-6736618301f9
---
With .Checkbox, .Radio `flexwrap` changed to `nowrap`:
https://github.com/dequelabs/cauldron/assets/60084578/ee399c8d-88c7-4b37-be61-2e2b4403bb21
w/ 4th option under wrapping line:
https://github.com/dequelabs/cauldron/assets/60084578/4dbaa581-63a3-41e5-9a02-d0033e09c6e0
---
With .Checkbox, .Radio `flexwrap` changed to `nowrap` and .Radio__overlay given `align-self` of `flex-start` (implemented):
https://github.com/dequelabs/cauldron/assets/60084578/6142d258-e011-451f-9427-bff88b6bcee9
w/ 4th option under wrapping line: …

fix(styles): fix overflow styling on Radio Group and Checkbox and align styles with Pattern Library

---

packages/styles/button.css
packages/styles/tag.css

I fixed the thicker focus ring for button tags and corrected the border when in dark mode (it should be noted that it is still barely visible on the current background which differs from the background color in UXPin).
Closes: https://github.com/dequelabs/cauldron/issues/1055

fix: sync Tag component with uxpin

---

packages/styles/forms.css

Relates to bug noted in [this Slack thread](https://deque.slack.com/archives/G017VP5SCUB/p1690478003393319)
Reverts [changes to Error class styles](https://github.com/dequelabs/cauldron/pull/1110/files#r1276602901), and scopes new changes to their respective elements

fix(styles): fix bug where Error class changes are applied globally

---

packages/react/src/components/Checkbox/index.tsx
packages/react/src/components/RadioGroup/index.tsx
packages/styles/forms.css

It looks like we got a little too aggressive with the change here as we should've added the new label as opposed to removing the old one.

fix(react): ensure that Field__label remains for Radio/Checkbox for better backwards compatibility

---

docs/pages/components/Table.mdx
packages/react/src/components/Icon/icons/table-sort-ascending.svg
packages/react/src/components/Icon/icons/table-sort-descending.svg
packages/styles/table.css

- adds thickness to bordered tables to match UXPin designs
- adds a note for recommended best practices when sorting tables
- adjusts the table-sort-ascending and table-sort-descending icons to match UXPin designs
Closes Issue: #1053 
Testing:
Confirm bordered table borders and sort icons [now match their UXPIN counterparts](https://app.uxpin.com/design-system/c933c74928e2195cc540/ui-patterns/213536)

fix(table): adjust border table thickness and sortable table icon

---

docs/components/ComponentLayout.css

Component props were sometimes wrapping in the middle of of the prop name. Updating that column/item to not wrap should help make these look a little bit cleaner and should not introduce a11y overflow issues as prop names are generally fairly short.

docs: prevent propName from wrapping in component props

---

package.json
yarn.lock

The version of prettier we were using was pretty outdated and choking on "newer" typescript things, like `import type { ... }`.

chore: update prettier to use ^2

---

.babelrc
package.json
packages/react/.babelrc
packages/react/package.json
packages/react/src/components/Accordion/Accordion.tsx
packages/react/src/components/FieldWrap/index.tsx
packages/react/src/components/IconButton/index.tsx
packages/react/src/components/LoaderOverlay/index.tsx
packages/react/src/components/Notice/index.tsx
packages/react/src/components/Panel/Panel.tsx
packages/react/src/components/Panel/PanelContent.tsx
packages/react/src/components/Panel/PanelHeader.tsx
packages/react/src/components/SideBar/SideBarItem.tsx
packages/react/src/components/Tabs/Tab.tsx
packages/react/src/components/Tabs/TabPanel.tsx
packages/react/src/components/TopBar/TopBarTrigger.tsx
packages/react/src/components/TwoColumnPanel/TwoColumnPanel.tsx
packages/react/yarn.lock
yarn.lock

General cleanup of typescript/babel dependencies. Removed a few unused babel plugins, but there were some issues with `import type...` on #1167 that I was trying to resolve here separately.

chore: upgrade babel/typescript to support latest features

---

docs/pages/components/Link.mdx

Fixes a typo where "button" was spelled incorrectly.

docs: button typo

---

docs/pages/components/TextField.mdx
packages/styles/forms.css

Found a color contrast issue in dark mode when TextField was an an error state and required. Matching the color with what's currently in our design system.

fix(styles): fix color contrast issue for required text on TextField with error

---

docs/pages/components/Popover.mdx
packages/react/__tests__/src/components/Popover/index.js
packages/react/src/components/Popover/index.tsx
packages/react/src/index.ts
packages/styles/index.css
packages/styles/popover.css

feat(Popover): add new component

---

packages/styles/button.css

Closes #1156
Updated the light theme hover button tag border to be #333 for button tags

fix: corrected color of button tags on hover in light theme.

---

docs/pages/components.mdx
docs/pages/components/Notice.mdx
docs/pages/components/OptionsMenu.mdx
docs/pages/components/Pagination.mdx
docs/pages/components/Panel.mdx
docs/pages/components/Pointout.mdx
docs/pages/components/Popover.mdx
docs/pages/components/ProgressBar.mdx
docs/pages/components/RadioGroup.mdx
docs/pages/components/Scrim.mdx
docs/pages/components/Select.mdx
docs/pages/components/Stepper.mdx
docs/pages/components/Tabs.mdx
docs/pages/components/Toast.mdx
docs/pages/components/Tooltip.mdx
docs/pages/components/TooltipTabstop.mdx
docs/pages/components/TopBar.mdx
docs/pages/components/TwoColumnPanel.mdx
docs/pages/intro.mdx
docs/pages/styles.mdx
docs/pages/theming.mdx

This PR fixes typos, acronyms, and rewords some things in sections for all of the docs pages.

docs: fix grammar and typos

---

packages/react/rollup.config.js
packages/react/src/components/Code/index.tsx

It appears something in the [npm changes with babel/rollup](https://github.com/dequelabs/cauldron/compare/v5.7.1...v5.8.0) caused react-syntax-highlighter to be pulled in as a dependency in the production bundle instead of inlined. Using the cjs dist of react-syntax-highlighter should prevent this issue from occuring.

fix(react): prevent esm modules from appearing in cjs dist

---

docs/components/ComponentLayout.css

docs: fix table of contents not scrolling when vertically overflowing

---

docs/pages/components/IconButton.mdx

docs: fix incorrect accessible labels for icon button documentation

---

CONTRIBUTING.md
docs/pages/intro.mdx
packages/react/README.md

Slight re-organization of documentation. I noticed that [npm documentation](https://www.npmjs.com/package/@deque/cauldron-react) wasn't really a great introduction to Cauldron and wanted to spruce it up a bit. I moved the server-side render section to the contribution readme and pointed directly to our documentation site from the package readme.

docs: clean up readme and package documentation

---

packages/styles/notice.css

closes MY OCD with the icon alignment

fix(styles): align Notice icon to top when text is wrapped

---

packages/styles/table.css

BREAKING CHANGE: The TableHeader sort button text colors do not change when ascending or descending, per the UX Pin. The removed styles were overriding with the same hex value for light or dark mode.
https://preview.uxpin.com/4052c8b6f05ce03e28813f28deb3a682950c2ac6#/pages/140808126/simulate/sitemap
https://cauldron.dequelabs.com/components/Table

fix(styles): clean up table sort button styles

---

docs/components/CopyToClipboardButton.tsx

docs: fix issue where body would become focused when copying an example instead of the toast

---

packages/styles/combobox.css

Selected Combobox options have a color contrast issue with the text of the current selected option:

fix(styles): fix color contrast issue with selected Combobox text

---

rfcs.md

Per our recent office hours, we wanted a clearer definition to an "approved" RFC proposal.

docs: update RFC approval process

---

packages/styles/dialog.css

I noticed that the dialog header had some issues when text was wrapping, this adjust the spacing to correctly wrap long dialog titles.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix(styles): fix layout issues with dialog header when wrapping

---

docs/components/ComponentLayout.css
e2e/accessibility.ts
package.json
yarn.lock

chore: include wcag22aa as part of accessibility checks

---

.github/workflows/preview-cleanup.yml
.github/workflows/preview.yml

The action frequently fails on master, and we really only need previews against pull requests as `develop` will always have the latest branch.

chore: prevent preview action from running against master branch

---

packages/react/src/components/Combobox/ComboboxOption.tsx

Noticed that combobox would through an error when text matching on empty options, e.g. `<ComboboxOption></ComboboxOption>`

fix(react): prevent error for ComboboxOption when text contents are empty

---

.github/dependabot.yml

Since many of the GitHub Actions versions in this repo are older, this PR adds a Dependabot config for updating dependencies for GitHub Actions similar to how it's done in `axe-core`.
https://github.com/dequelabs/axe-core/blob/develop/.github/dependabot.yml#L3-L16

chore(dependabot): monthly updates for actions

---

.github/actions/dependencies/action.yml

Publishing is currently failing in `develop`: https://github.com/dequelabs/cauldron/actions/runs/6882188075/job/18720262812
Looks like I forgot to include the registry url for the `setup-node` step.

ci: fix missing registry-url for node step in github action

---

packages/react/package.json

Code coverage was previously including `lib/**` files, so this scopes it to just use `src/**` files.

test: fix code coverage

---

docs/pages/components/IconButton.mdx
packages/react/src/components/IconButton/index.tsx
packages/styles/button.css
packages/styles/icon-button.css

Closes: #1175 and #969.
Also PR closes partly (only for icon-button): #938

fix(style): Synced styles and added large variant of IconButton

---

packages/react/src/components/Combobox/Combobox.test.tsx
packages/react/src/components/Combobox/Combobox.tsx

fix(Combobox): prevent default event  when Combobox listbox is expanded on enter keypress

---

packages/styles/dialog.css

Noticed there was a visual regression with the close button:

fix(styles): fix incorrect icon size with Dialog close buttons

---

packages/react/src/components/Combobox/Combobox.test.tsx
packages/react/src/components/Combobox/Combobox.tsx

I realized that combobox was missing axe tests and also missing the incorrect ref type while writing the tests.

fix(Combobox): fix incorrect type for Combobox ref

---

packages/react/__tests__/src/components/IconButton/index.js
packages/react/__tests__/src/components/LoaderOverlay/index.js
packages/react/__tests__/src/components/MenuBar/index.js
packages/react/__tests__/src/components/OptionsMenu/OptionsMenuList.js
packages/react/__tests__/src/components/Popover/index.js
packages/react/__tests__/src/components/Select/index.js
packages/react/__tests__/src/components/Tabs/Tabs.js
packages/react/__tests__/src/components/TagButton/index.js
packages/react/__tests__/src/components/Toast/index.js
packages/react/__tests__/src/components/Tooltip/index.js
packages/react/__tests__/src/components/TooltipTabstop/index.js
packages/react/jest.config.ts
packages/react/package.json
packages/react/yarn.lock

Slight test refactor to get jest upgraded including:
- updating jest and @type/jest to 29.x
- setting `testEnvironment` to `jsdom`
- move jest configuration out of package.json and into separate config file
There were a number of tests failing likely do to the jsdom environment change, related to `document.activeElement`. I realize the changes in the test may not be the ideal way to test for these changes, but I did not want to spend a lot of time as we will be addressing testing once we update tests to use react-testing-library.

test: upgrade jest dependencies to 29.x

---

packages/react/src/components/TextField/index.tsx

I noticed this while updating the tests in #1337 that the input's `className` was getting clobbered on `TextField` when passed as a prop. #1337 will handle the tests, while this PR is just for the fix.

fix(TextField): prevent className clobbering on TextField input

---

packages/styles/forms.css

* CSS adjustment to use the default hover cursor on non-intractable disabled checkboxes
Closes issue: #1339

fix(react): use default hover cursor when checkboxes are disabled

---

CONTRIBUTING.md

I noticed a typo in the contributing guide. It says that new unit tests should be written in Enzyme, but I think it's meant to be React Testing Library.

docs(CONTRIBUTING.md): fix typo regarding writing new tests with RTL

---

CONTRIBUTING.md

Undoing a typo, and bringing more prominence to the test migration.

docs: call out enzyme to rtl migration

---

packages/react/src/components/Breadcrumb/index.test.tsx

Issue #1159
This PR switches the Line tests to React Testing Library.
- Run yarn test
- See that there are coverage percentages in the table
- Verify that the tests are converted properly

test: switch breadcrumb tests to react testing library

---

.github/workflows/vpat-labeler.yml

Action is still failing due to labels being required: https://github.com/dequelabs/cauldron/actions/runs/8086963518

chore: include required labels for vpat issue labeler

---

docs/index.css
docs/pages/components/SearchField.mdx
packages/react/src/components/SearchField/SearchField.test.tsx
packages/react/src/components/SearchField/index.tsx
packages/styles/text-field-wrapper.css

closes https://github.com/dequelabs/cauldron/issues/1358

feat(react): Add property to include trailing children for SearchField component

---

docs/pages/components/TwoColumnPanel.mdx

docs: fix associated label for the twocolumn region example

---

docs/components/Spacing.css

docs: fix color contrast for spacing indicator

---

packages/react/src/components/SearchField/SearchField.test.tsx
packages/react/src/components/SearchField/index.tsx
packages/react/src/components/internal/TextFieldWrapper/TextFieldWrapper.test.tsx
packages/styles/text-field-wrapper.css

fix(react): prevent search field input from inheriting unintended styles from default TextField

---

.github/workflows/vpat-create.yml

The most recent vpat generation didn't pick up vpat issues, it looks like we were just missing the appropriate vpat label.

ci: fix vpat creation

---

docs/pages/components/IconButton.mdx

Noticed that we were using `class` here which isn't valid in JSX but wasn't actually necessary.

docs: fix invalid JSX with IconButton

---

e2e/Dockerfile
package.json
yarn.lock

Playwright is currently failing all screenshots, so this is changing the build to pull the latest version when building the docker file.

chore: update playwright dependencies

---

packages/react/src/components/Pagination/Pagination.tsx

This was using the deprecated pattern of tooltip placement, leading to a bunch of unnecessary logging happening in tests (and probably in development) when using Pagination.

chore: update pagination to use updated IconButton props

---

packages/react/src/components/Toast/toast.test.tsx

I noticed that a couple of these tests had timeout assertions that weren't being waited upon, leading to some PRs failing over the past week or so.

chore: fix flaky toast tests

---

.github/workflows/sync-branches.yml

I do not frequently work on Cauldron, so I probably shouldn't be involved in its release process.

ci: Remove myself from sync branches workflow

---

packages/react/src/components/LoaderOverlay/index.tsx

- This pull request removes the loader overlay's `focusOnInitialRender`'s dependency on setTimeout + the loader's ref as a dependency in the `useEffect`'s dependency array. 
- closes: #747 (replaces #833)

fix(react): make focusOnInitialRender work without setTimeout

---

packages/react/src/components/Combobox/Combobox.test.tsx
packages/react/src/components/Combobox/Combobox.tsx

fix: set `value` rather than `label` when using `onChange` and `onSelectionChange` with `Combobox`

---

packages/react/src/components/IconButton/IconButton.test.tsx
packages/react/src/components/IconButton/index.tsx

closes #1490 
The original intention was to only allow for `button` or `a` elements to be passed in here. Unfortunately, this can be somewhat restrictive since the intrinsic element type is not known leading to errors when trying to pass something in like a link from React Router. We lose a little bit of safety here, but we do try to do some duck typing in the component to figure out if the role should be a `button` or `link` so we're not losing too much by loosening the type restrictions.

fix(IconButton): loosen polymorphic type to allow for any type of JSXElement

---

packages/react/src/components/Combobox/Combobox.test.tsx
packages/react/src/components/Combobox/Combobox.tsx

fix(Combobox): fix issue where autocomplete automatic does not fire selection event

---

packages/react/jest.config.ts
packages/react/src/utils/polymorphicComponent.test.tsx
packages/react/src/utils/useSharedRef.test.tsx

Issue https://github.com/dequelabs/cauldron/issues/1159
This PR switches the `useSharedRef` tests to React Testing Library.
Validation steps
Run yarn test
See that there are coverage percentages in the table
Verify that the tests are converted properly

test: moved `useSharedRef` tests from `Enzyme` to `RTL`

---

packages/react/src/utils/rndid/index.test.ts

Issue https://github.com/dequelabs/cauldron/issues/1159
This PR switches the `utils.rndid` tests to React Testing Library.
Validation steps
Run yarn test
See that there are coverage percentages in the table
Verify that the tests are converted properly

test: moved `rndid` to RTL/typescript tests

---

.github/dependabot.yml

closes #1529
For now we'll ignore specific ESM dependencies which are incompatible with the way we import modules.

chore: ignore esm dependency updates

---

package.json

Noticed dependabot was requesting a bump here: https://github.com/dequelabs/cauldron/pull/1545, but we are already using `@fontsource/roboto` so these dependencies are likely outdated:
https://github.com/dequelabs/cauldron/blob/7e01173a2d12b1f09a89678205795d023418eaa7/package.json#L55-L57

chore: remove unused fontsource packages

---

.github/dependabot.yml

We likely want to be updating `babel*` dependencies in tandem.

chore: group babel dependencies under dependabot

---

README.md
docs/readme.md

Fix typo and capitalization in `docs/readme.md` and `README.md`.

docs: grammar and typos in readme

---

packages/styles/button.css

This is flagging these selectors as deprecated so they can be removed in a future version of Cauldron.
ref #1591

feat(styles): flag DefinitionButton as a deprecated class

---

docs/pages/components/Notice.mdx
packages/react/src/components/Notice/index.test.tsx
packages/react/src/components/Notice/index.tsx
packages/styles/notice.css

Closes: https://github.com/dequelabs/cauldron/issues/1577

fix: synced `Notice` component with design

---

packages/react/src/components/Dialog/Dialog.test.tsx
packages/react/src/components/Dialog/index.tsx
packages/react/src/components/Tooltip/index.tsx

Fixes an issue where, when a tooltip is within a modal, the modal 'eats' the escape key event and closes first, preventing the tooltip from closing when it has focus.
Closes: #1597
Part of: dequelabs/comply#6311

fix(react): Dialog closes instead of contained tooltip on escape key

---

packages/react/src/components/Notice/index.test.tsx
packages/react/src/components/Notice/index.tsx

fix(Notice): allow className to be passed into Notice component

---

playwright-ct.config.ts

Even while using docker, it seems there's still some flaky issues with visual diffs with screenshots, see:
- https://github.com/microsoft/playwright/issues/8161
- https://github.com/microsoft/playwright/issues/13873
We can undo this change for now, but may want to investigate addressing this in the future as we should be able to perform strict pixel matching when using docker images.

chore: undo strict pixel matching

---

packages/react/src/components/OptionsMenu/OptionsMenu.tsx

With the new update to React 17, this component requires the `onSelect` prop. This can be changed to optional since it does not need to be used to function properly.

fix: onSelect prop for OptionsMenu is optional

---

packages/react/src/components/BottomSheet/BottomSheet.test.tsx
packages/react/src/components/Checkbox/Checkbox.test.tsx
packages/react/src/components/Drawer/Drawer.test.tsx
packages/react/src/components/IconButton/IconButton.test.tsx
packages/react/src/components/MenuItem/index.test.tsx
packages/react/src/components/Pagination/index.test.tsx
packages/react/src/components/Popover/index.test.tsx
packages/react/src/components/RadioGroup/RadioGroup.test.tsx
packages/react/src/components/Scrim/index.test.tsx
packages/react/src/components/SearchField/SearchField.test.tsx
packages/react/src/components/TextEllipsis/TextEllipsis.test.tsx
packages/react/src/components/Toast/toast.test.tsx
packages/react/src/components/Tooltip/Tooltip.test.tsx
packages/react/src/components/TooltipTabstop/index.test.tsx
packages/react/src/components/TwoColumnPanel/TwoColumnPanel.test.tsx
packages/react/src/contexts/theme.test.tsx

Test output has been very difficult to read because it was interspersed with `When testing, code that causes React state updates should be wrapped into act(...)`. This makes it hard to narrow down issues when tests are failing because of all of these console messages.
This PR cleans up these test cases where this error is occurring to make the test output more readable.

test: fix act errors in react tests

---

packages/react/src/contexts/theme.test.tsx

The theme test will toss out a `console.error` which we don't really need to see...

test: remove unnecessary console messages in theme test

---

packages/react/src/components/SideBar/SideBarItem.tsx

Fixing the following error: 
> console.error
>      Warning: SideBarItem: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
>          at SideBarItem (/home/runner/work/cauldron/cauldron/packages/react/src/components/SideBar/SideBarItem.tsx:12:8)
>          at ul
>          at nav
>          at ClickOutsideListener > (/home/runner/work/cauldron/cauldron/packages/react/src/components/ClickOutsideListener/index.tsx:17:5)
at SideBar (/home/runner/work/cauldron/cauldron/packages/react/src/components/SideBar/SideBar.tsx:33:5)

fix(react): remove defaultProps from sidebar, use default parameters instead

---

docs/pages/components/Table.mdx
packages/react/src/components/Table/Table.tsx
packages/react/src/components/Table/index.test.tsx

Table column definitions was missing "max-width" configuration as well as not having the correct values set when using a numeric width.

feat(react): add max-width column configuration to Table grids

---

packages/react/src/components/Listbox/Listbox.tsx

This addresses an obscure issue when using controlled listboxes. The behavior basically was whenever the value would change, it would always reset the active element to the first selected element in the list causing the focus to reset on the element whenever new selections were made.

fix(react): fix a11y active-descendant issue with controlled Listboxes

---

packages/react/src/components/MenuItem/index.test.tsx

This removes the `Error: Not implemented: navigation (except hash changes)` error that happens within the menu item test.

test: remove noisy console error for MenuItem

---

docs/pages/components/AnchoredOverlay.mdx
packages/react/src/components/AnchoredOverlay/AnchoredOverlay.test.tsx
packages/react/src/components/AnchoredOverlay/index.tsx

Focus trap settings on AnchoredOverlay should be able to be configured for outside projects that do not have access to Cauldron internals.

feat(react): add focusTrap options to AnchoredOverlay

---

docs/pages/components/RadioCardGroup.mdx

This pattern is deprecated and should not be used going forward. We have a desired pattern to move forward with but want to at least document this as deprecated https://github.com/dequelabs/cauldron/issues/1289

fix(react): deprecate RadioCardGroup component

---

.github/workflows/vpat-sla.yaml

I noticed that the vpat:sla action was removing labels when a ticket got updated. We always want those labels to remain on the issue.

chore: prevent stale label from being removed on updates for vpat sla

---

e2e/helpers/playwright.ts
package.json

I found this when debugging why the Playwright tests weren't failing after changing a CSS var in https://github.com/dequelabs/cauldron/pull/1808.

chore: remove duplicate e2e volume mount

---

packages/styles/drawer.css

Closes https://github.com/dequelabs/cauldron/issues/1834
Uses variables to set the timing and animation function for the `Drawer`.
- Go to https://pr-1835.d15792l1n26ww3.amplifyapp.com/components/Drawer
- Verify that the CSS variables and default values are correct

feat(styles): update drawer animation

---

.github/CODEOWNERS
CONTRIBUTING.md

Using a unified design team, no special team for cauldron needed.

chore: update design team references

---

docs/pages/components/PageHeader.mdx
docs/pages/components/SectionHeader.mdx
packages/react/src/components/PageHeader/PageHeader.test.tsx
packages/react/src/components/PageHeader/index.tsx
packages/react/src/components/SectionHeader/SectionHeader.test.tsx
packages/react/src/components/SectionHeader/index.tsx
packages/react/src/index.ts
packages/styles/index.css
packages/styles/page-header.css
packages/styles/section-header.css
packages/styles/variables.css

Closes: https://github.com/dequelabs/cauldron/issues/1812
This pull request introduces the new `PageHeader` and `SectionHeader` components in the `@deque/cauldron-react` library, along with their respective documentation, tests, and styles. These components are designed to provide consistent and customizable headers for pages and sections within the application.
**New Components:**
* `PageHeader` component: A header component for pages that includes a heading, optional overline, description, and actions.
* `SectionHeader` component: A header component for sections that includes a heading, optional description, and actions.
**Styles:**
* Added CSS styles for `PageHeader` to define layout, typography, and theme-specific colors.
* Added CSS styles for `SectionHeader` to define layout, …

feat(react, styles): add `PageHeader` and `SectionHeader` components with styles and tests

---

packages/react/jest.config.ts
packages/react/package.json

I noticed we didn't have code coverage setup/configured correctly as it was including screenshots as part of coverage and wasn't failing if below the threshold. Just a quick fix to actually enforce coverage with jest configuration and to ensure we're covering the right things.

chore: fix code coverage

---

packages/styles/empty-state.css

@anastasialanz pointed out this was different.

fix(styles): use consistent variable naming for empty state

---

packages/react/src/components/Stepper/index.tsx

Close: https://github.com/dequelabs/walnut/issues/11181
This pull request includes a minor update to the `Stepper` component in the `packages/react` library. The `StepperProps` interface has been updated to use `React.OlHTMLAttributes` instead of `React.HTMLAttributes` for better type specificity.
* [`packages/react/src/components/Stepper/index.tsx`](diffhunk://#diff-113f83d3733fab97a662b2ea4f3e74bb9b689d7c21ad137c1d92a137b5122c21L106-R106): Replaced `React.HTMLAttributes<HTMLOListElement>` with `React.OlHTMLAttributes<HTMLOListElement>` in the `StepperProps` interface to ensure the attributes are specific to ordered lists.

fix(Stepper): fixed types for Stepper component

---

packages/styles/description-list.css

ref #2026
The overflow value is fixed, but this is still displaying a scrollbar in some instances. The change here ensures that the element still remains visible with no visible scrollbar.

fix(styles): use correct overflow value for description list

---

packages/react/src/components/ActionMenu/screenshots.e2e.tsx
packages/styles/action-menu.css

fix(styles): set default max-height of action menus to prevent excessive overflow

---

packages/styles/tabs.css

Closes: https://github.com/dequelabs/cauldron/issues/2098
This pull request updates the tab panel styling in `packages/styles/tabs.css` to improve visual consistency and theme support. The most important changes are grouped below:
**Theme Variable Updates:**
* Added a new CSS variable `--tab-panel-background-color` for both light and dark themes, allowing distinct background colors for tab panels. [[1]](diffhunk://#diff-dbc8cbb7e8cb0112a62b580b701c9f621255ee937a80703b105476777415e0c2R6) [[2]](diffhunk://#diff-dbc8cbb7e8cb0112a62b580b701c9f621255ee937a80703b105476777415e0c2R19)
**Tab Panel Styling:**
* Updated the `.TabPanel` background color to use the new `--tab-panel-background-color` variable instead of `--tab-active-background-color`, ensuring better separation between active tab and …

fix(style): update tab panel background colors for light and dark themes

---

packages/styles/action-menu.css
packages/styles/variables.css

closes #2108 
Example of the action menu now appearing above the topbar menu:

fix(styles): move ActionMenu to top most z-index layer
